/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: 120.c                                                 *
* Font:        微软雅黑                                              *
* Height:      120                                                   *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 120                                           *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: G:\Users\Administrator\Desktop\AM-128B.txt      *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Font120;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Font120_002D[ 40] = { /* code 002D, HYPHEN-MINUS */
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font120_0031[414] = { /* code 0031, DIGIT ONE */
  ________,________,________,_XXXX___,________,________,
  ________,________,_____XXX,XXXXX___,________,________,
  ________,________,XXXXXXXX,XXXXX___,________,________,
  ________,___XXXXX,XXXXXXXX,XXXXX___,________,________,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXX___,________,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,________,
  XXXXXXXX,XXXX___X,XXXXXXXX,XXXXX___,________,________,
  XXXXXXX_,_______X,XXXXXXXX,XXXXX___,________,________,
  XX______,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Font120_0032[414] = { /* code 0032, DIGIT TWO */
  ________,________,_XXXXXXX,XXXXX___,________,________,
  ________,____XXXX,XXXXXXXX,XXXXXXXX,X_______,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,
  _______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,________,_XXXXXXX,XXXXXXXX,XXXX____,
  ___XXXXX,XXXX____,________,___XXXXX,XXXXXXXX,XXXX____,
  ___XXXXX,XX______,________,____XXXX,XXXXXXXX,XXXX____,
  ___XXXXX,________,________,_____XXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,________,______XX,XXXXXXXX,XXXXX___,
  ___XX___,________,________,______XX,XXXXXXXX,XXXXX___,
  ___X____,________,________,_______X,XXXXXXXX,XXXXX___,
  ________,________,________,_______X,XXXXXXXX,XXXXX___,
  ________,________,________,_______X,XXXXXXXX,XXXXX___,
  ________,________,________,_______X,XXXXXXXX,XXXXX___,
  ________,________,________,_______X,XXXXXXXX,XXXXX___,
  ________,________,________,_______X,XXXXXXXX,XXXXX___,
  ________,________,________,_______X,XXXXXXXX,XXXXX___,
  ________,________,________,_______X,XXXXXXXX,XXXX____,
  ________,________,________,______XX,XXXXXXXX,XXXX____,
  ________,________,________,______XX,XXXXXXXX,XXXX____,
  ________,________,________,______XX,XXXXXXXX,XXX_____,
  ________,________,________,_____XXX,XXXXXXXX,XXX_____,
  ________,________,________,____XXXX,XXXXXXXX,XX______,
  ________,________,________,____XXXX,XXXXXXXX,XX______,
  ________,________,________,___XXXXX,XXXXXXXX,X_______,
  ________,________,________,__XXXXXX,XXXXXXXX,X_______,
  ________,________,________,_XXXXXXX,XXXXXXXX,________,
  ________,________,________,_XXXXXXX,XXXXXXX_,________,
  ________,________,________,XXXXXXXX,XXXXXXX_,________,
  ________,________,_______X,XXXXXXXX,XXXXXX__,________,
  ________,________,______XX,XXXXXXXX,XXXXX___,________,
  ________,________,_____XXX,XXXXXXXX,XXXX____,________,
  ________,________,____XXXX,XXXXXXXX,XXX_____,________,
  ________,________,___XXXXX,XXXXXXXX,XX______,________,
  ________,________,__XXXXXX,XXXXXXXX,X_______,________,
  ________,________,_XXXXXXX,XXXXXXXX,________,________,
  ________,________,XXXXXXXX,XXXXXXX_,________,________,
  ________,_______X,XXXXXXXX,XXXXXX__,________,________,
  ________,______XX,XXXXXXXX,XXXXX___,________,________,
  ________,_____XXX,XXXXXXXX,XXXX____,________,________,
  ________,___XXXXX,XXXXXXXX,XXX_____,________,________,
  ________,__XXXXXX,XXXXXXXX,XX______,________,________,
  ________,_XXXXXXX,XXXXXXXX,X_______,________,________,
  ________,XXXXXXXX,XXXXXXXX,________,________,________,
  _______X,XXXXXXXX,XXXXXXX_,________,________,________,
  ______XX,XXXXXXXX,XXXXXX__,________,________,________,
  _____XXX,XXXXXXXX,XXXXX___,________,________,________,
  ____XXXX,XXXXXXXX,XXX_____,________,________,________,
  ___XXXXX,XXXXXXXX,XX______,________,________,________,
  __XXXXXX,XXXXXXXX,X_______,________,________,________,
  _XXXXXXX,XXXXXXXX,________,________,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Font120_0038[420] = { /* code 0038, DIGIT EIGHT */
  ________,________,___XXXXX,XXXXXX__,________,________,
  ________,_______X,XXXXXXXX,XXXXXXXX,XX______,________,
  ________,____XXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  _______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ____XXXX,XXXXXXXX,XXXXX___,____XXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXX_____,______XX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,X_______,_______X,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,________,________,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,________,________,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXX_,________,________,_XXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXX_,________,________,_XXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXX_,________,________,_XXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXX_,________,________,_XXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXX_,________,________,_XXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXX_,________,________,_XXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,________,________,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,________,________,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,X_______,_______X,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XX______,______XX,XXXXXXXX,XXXX____,
  ____XXXX,XXXXXXXX,XXX_____,_____XXX,XXXXXXXX,XXXX____,
  _____XXX,XXXXXXXX,XXXXX___,___XXXXX,XXXXXXXX,XXX_____,
  ______XX,XXXXXXXX,XXXXXXX_,_XXXXXXX,XXXXXXXX,XX______,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ________,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,___XXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  ________,____XXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,
  ________,______XX,XXXXXXXX,XXXXXXXX,XX______,________,
  ________,____XXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _____XXX,XXXXXXXX,XXXXXXX_,_XXXXXXX,XXXXXXXX,XXXX____,
  ____XXXX,XXXXXXXX,XXXX____,____XXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXX_____,_____XXX,XXXXXXXX,XXXXX___,
  __XXXXXX,XXXXXXXX,X_______,_______X,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,________,________,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXX_,________,________,_XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,________,________,_XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXX__,________,________,__XXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXX__,________,________,__XXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXX___,________,________,___XXXXX,XXXXXXXX,
  XXXXXXXX,XXXXX___,________,________,___XXXXX,XXXXXXXX,
  XXXXXXXX,XXXXX___,________,________,___XXXXX,XXXXXXXX,
  XXXXXXXX,XXXXX___,________,________,___XXXXX,XXXXXXXX,
  XXXXXXXX,XXXXX___,________,________,___XXXXX,XXXXXXXX,
  XXXXXXXX,XXXXX___,________,________,___XXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXX__,________,________,__XXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXX__,________,________,__XXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,________,________,_XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,________,________,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XX______,_______X,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXX____,____XXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  ________,_____XXX,XXXXXXXX,XXXXXXXX,XX______,________,
  ________,________,_XXXXXXX,XXXXXX__,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font120_0041[612] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,________,________,_XXXXXXX,XXXXXXXX,XXX_____,________,________,________,
  ________,________,________,XXXXXXXX,XXXXXXXX,XXXX____,________,________,________,
  ________,________,________,XXXXXXXX,XXXXXXXX,XXXX____,________,________,________,
  ________,________,________,XXXXXXXX,XXXXXXXX,XXXX____,________,________,________,
  ________,________,_______X,XXXXXXXX,XXXXXXXX,XXXXX___,________,________,________,
  ________,________,_______X,XXXXXXXX,XXXXXXXX,XXXXX___,________,________,________,
  ________,________,_______X,XXXXXXXX,XXXXXXXX,XXXXX___,________,________,________,
  ________,________,______XX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,________,________,
  ________,________,______XX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,________,________,
  ________,________,______XX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,________,________,
  ________,________,_____XXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,________,________,
  ________,________,_____XXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,________,________,
  ________,________,____XXXX,XXXXXXXX,X_XXXXXX,XXXXXXX_,________,________,________,
  ________,________,____XXXX,XXXXXXXX,X_XXXXXX,XXXXXXXX,________,________,________,
  ________,________,____XXXX,XXXXXXXX,X_XXXXXX,XXXXXXXX,________,________,________,
  ________,________,___XXXXX,XXXXXXXX,__XXXXXX,XXXXXXXX,________,________,________,
  ________,________,___XXXXX,XXXXXXXX,___XXXXX,XXXXXXXX,X_______,________,________,
  ________,________,___XXXXX,XXXXXXXX,___XXXXX,XXXXXXXX,X_______,________,________,
  ________,________,__XXXXXX,XXXXXXXX,___XXXXX,XXXXXXXX,XX______,________,________,
  ________,________,__XXXXXX,XXXXXXX_,____XXXX,XXXXXXXX,XX______,________,________,
  ________,________,_XXXXXXX,XXXXXXX_,____XXXX,XXXXXXXX,XX______,________,________,
  ________,________,_XXXXXXX,XXXXXXX_,____XXXX,XXXXXXXX,XXX_____,________,________,
  ________,________,_XXXXXXX,XXXXXX__,_____XXX,XXXXXXXX,XXX_____,________,________,
  ________,________,XXXXXXXX,XXXXXX__,_____XXX,XXXXXXXX,XXX_____,________,________,
  ________,________,XXXXXXXX,XXXXXX__,_____XXX,XXXXXXXX,XXXX____,________,________,
  ________,________,XXXXXXXX,XXXXX___,_____XXX,XXXXXXXX,XXXX____,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,______XX,XXXXXXXX,XXXX____,________,________,
  ________,_______X,XXXXXXXX,XXXXX___,______XX,XXXXXXXX,XXXXX___,________,________,
  ________,_______X,XXXXXXXX,XXXX____,______XX,XXXXXXXX,XXXXX___,________,________,
  ________,______XX,XXXXXXXX,XXXX____,_______X,XXXXXXXX,XXXXX___,________,________,
  ________,______XX,XXXXXXXX,XXXX____,_______X,XXXXXXXX,XXXXXX__,________,________,
  ________,_____XXX,XXXXXXXX,XXX_____,_______X,XXXXXXXX,XXXXXX__,________,________,
  ________,_____XXX,XXXXXXXX,XXX_____,________,XXXXXXXX,XXXXXX__,________,________,
  ________,_____XXX,XXXXXXXX,XXX_____,________,XXXXXXXX,XXXXXXX_,________,________,
  ________,____XXXX,XXXXXXXX,XX______,________,XXXXXXXX,XXXXXXX_,________,________,
  ________,____XXXX,XXXXXXXX,XX______,________,_XXXXXXX,XXXXXXXX,________,________,
  ________,____XXXX,XXXXXXXX,XX______,________,_XXXXXXX,XXXXXXXX,________,________,
  ________,___XXXXX,XXXXXXXX,X_______,________,_XXXXXXX,XXXXXXXX,________,________,
  ________,___XXXXX,XXXXXXXX,X_______,________,__XXXXXX,XXXXXXXX,X_______,________,
  ________,__XXXXXX,XXXXXXXX,X_______,________,__XXXXXX,XXXXXXXX,X_______,________,
  ________,__XXXXXX,XXXXXXXX,________,________,__XXXXXX,XXXXXXXX,X_______,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,
  ________,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,
  ________,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,
  ________,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  _______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  _______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  ______XX,XXXXXXXX,XXXXX___,________,________,______XX,XXXXXXXX,XXXXXX__,________,
  _____XXX,XXXXXXXX,XXXX____,________,________,______XX,XXXXXXXX,XXXXXX__,________,
  _____XXX,XXXXXXXX,XXXX____,________,________,_______X,XXXXXXXX,XXXXXX__,________,
  _____XXX,XXXXXXXX,XXXX____,________,________,_______X,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,XXXX____,________,________,_______X,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,XXX_____,________,________,________,XXXXXXXX,XXXXXXX_,________,
  ___XXXXX,XXXXXXXX,XXX_____,________,________,________,XXXXXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,XXX_____,________,________,________,XXXXXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,XX______,________,________,________,_XXXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXXXX,XX______,________,________,________,_XXXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,XX______,________,________,________,_XXXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,X_______,________,________,________,__XXXXXX,XXXXXXXX,X_______,
  _XXXXXXX,XXXXXXXX,X_______,________,________,________,__XXXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,X_______,________,________,________,__XXXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,________,________,________,________,___XXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,________,________,________,________,___XXXXX,XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Font120_0042[476] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXXX__,________,_XXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXXX__,________,____XXXX,XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXX__,________,______XX,XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXX__,________,_______X,XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXX__,________,_______X,XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXX__,________,________,XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXX__,________,________,XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXX__,________,________,XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXX__,________,________,XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXX__,________,________,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXXX__,________,________,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXXX__,________,_______X,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXXX__,________,_______X,XXXXXXXX,XXXXX___,________,
  XXXXXXXX,XXXXXX__,________,______XX,XXXXXXXX,XXXX____,________,
  XXXXXXXX,XXXXXX__,________,_____XXX,XXXXXXXX,XXXX____,________,
  XXXXXXXX,XXXXXX__,________,____XXXX,XXXXXXXX,XXX_____,________,
  XXXXXXXX,XXXXXX__,________,_XXXXXXX,XXXXXXXX,XX______,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXX__,________,____XXXX,XXXXXXXX,XXXXXXXX,________,
  XXXXXXXX,XXXXXX__,________,_______X,XXXXXXXX,XXXXXXXX,________,
  XXXXXXXX,XXXXXX__,________,________,XXXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXX__,________,________,_XXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXX__,________,________,__XXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXX__,________,________,__XXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXX__,________,________,___XXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXX__,________,________,___XXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXX__,________,________,___XXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXX__,________,________,___XXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXX__,________,________,___XXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXX__,________,________,___XXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXX__,________,________,__XXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXX__,________,________,__XXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXX__,________,________,_XXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXX__,________,________,XXXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXX__,________,______XX,XXXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXX__,________,____XXXX,XXXXXXXX,XXXXXXXX,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font120_004D[680] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXXXXXXX,XXXXXXXX,XXXXX___,________,________,________,________,_XXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXX__,________,________,________,________,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXX__,________,________,________,________,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXX__,________,________,________,________,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,________,________,________,_______X,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,________,________,________,_______X,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,________,________,________,_______X,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,________,________,________,______XX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,________,________,________,______XX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,________,________,________,_____XXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,________,________,_____XXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,________,________,_____XXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,________,____XXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,________,____XXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,________,____XXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX_XX,XXXXXXXX,XXX_____,________,________,___XXXXX,XXXXXX_X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX_XX,XXXXXXXX,XXX_____,________,________,___XXXXX,XXXXXX_X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX_XX,XXXXXXXX,XXX_____,________,________,__XXXXXX,XXXXXX_X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX_XX,XXXXXXXX,XXXX____,________,________,__XXXXXX,XXXXXX_X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX_XX,XXXXXXXX,XXXX____,________,________,__XXXXXX,XXXXXX_X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX__X,XXXXXXXX,XXXX____,________,________,_XXXXXXX,XXXXX__X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX__X,XXXXXXXX,XXXXX___,________,________,_XXXXXXX,XXXXX__X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX__X,XXXXXXXX,XXXXX___,________,________,_XXXXXXX,XXXXX__X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,XXXXXXXX,XXXXX___,________,________,XXXXXXXX,XXXX___X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,XXXXXXXX,XXXXXX__,________,________,XXXXXXXX,XXXX___X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,XXXXXXXX,XXXXXX__,________,________,XXXXXXXX,XXX____X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,_XXXXXXX,XXXXXXX_,________,_______X,XXXXXXXX,XXX____X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,_XXXXXXX,XXXXXXX_,________,_______X,XXXXXXXX,XXX____X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,_XXXXXXX,XXXXXXX_,________,______XX,XXXXXXXX,XX_____X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,__XXXXXX,XXXXXXXX,________,______XX,XXXXXXXX,XX_____X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,__XXXXXX,XXXXXXXX,________,______XX,XXXXXXXX,XX_____X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,___XXXXX,XXXXXXXX,________,_____XXX,XXXXXXXX,X______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,___XXXXX,XXXXXXXX,X_______,_____XXX,XXXXXXXX,X______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,___XXXXX,XXXXXXXX,X_______,_____XXX,XXXXXXXX,X______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,____XXXX,XXXXXXXX,X_______,____XXXX,XXXXXXXX,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,____XXXX,XXXXXXXX,XX______,____XXXX,XXXXXXXX,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,____XXXX,XXXXXXXX,XX______,___XXXXX,XXXXXXX_,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,_____XXX,XXXXXXXX,XXX_____,___XXXXX,XXXXXXX_,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,_____XXX,XXXXXXXX,XXX_____,___XXXXX,XXXXXXX_,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,______XX,XXXXXXXX,XXX_____,__XXXXXX,XXXXXX__,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,______XX,XXXXXXXX,XXXX____,__XXXXXX,XXXXXX__,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,______XX,XXXXXXXX,XXXX____,__XXXXXX,XXXXXX__,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,_______X,XXXXXXXX,XXXX____,_XXXXXXX,XXXXX___,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,_______X,XXXXXXXX,XXXXX___,_XXXXXXX,XXXXX___,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,_______X,XXXXXXXX,XXXXX___,_XXXXXXX,XXXXX___,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,XXXXXXXX,XXXXX___,XXXXXXXX,XXXX____,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,XXXXXXXX,XXXXXX__,XXXXXXXX,XXXX____,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,XXXXXXXX,XXXXXX__,XXXXXXXX,XXX_____,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,_XXXXXXX,XXXXXX_X,XXXXXXXX,XXX_____,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,_XXXXXXX,XXXXXX_X,XXXXXXXX,XXX_____,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,__XXXXXX,XXXXXX_X,XXXXXXXX,XX______,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,__XXXXXX,XXXXXXXX,XXXXXXXX,XX______,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,__XXXXXX,XXXXXXXX,XXXXXXXX,XX______,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,___XXXXX,XXXXXXXX,XXXXXXXX,X_______,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,___XXXXX,XXXXXXXX,XXXXXXXX,X_______,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,___XXXXX,XXXXXXXX,XXXXXXXX,X_______,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,____XXXX,XXXXXXXX,XXXXXXXX,________,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,____XXXX,XXXXXXXX,XXXXXXXX,________,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,_____XXX,XXXXXXXX,XXXXXXX_,________,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,_____XXX,XXXXXXXX,XXXXXXX_,________,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,_____XXX,XXXXXXXX,XXXXXXX_,________,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,______XX,XXXXXXXX,XXXXXX__,________,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,______XX,XXXXXXXX,XXXXXX__,________,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,______XX,XXXXXXXX,XXXXXX__,________,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,_______X,XXXXXXXX,XXXXX___,________,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,_______X,XXXXXXXX,XXXXX___,________,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,_______X,XXXXXXXX,XXXXX___,________,_______X,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,________,________,XXXXXXXX,XXXX____,________,_______X,XXXXXXXX,XXXXXX__};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_Font120_CharInfo[7] = {
   {  26,  10,   7,  65,  39, acGUI_Font120_002D } /* code 002D, HYPHEN-MINUS */
  ,{  43,  69,   7,  27,  56, acGUI_Font120_0031 } /* code 0031, DIGIT ONE */
  ,{  45,  69,   5,  27,  56, acGUI_Font120_0032 } /* code 0032, DIGIT TWO */
  ,{  48,  70,   4,  27,  56, acGUI_Font120_0038 } /* code 0038, DIGIT EIGHT */
  ,{  67,  68,   0,  28,  68, acGUI_Font120_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  50,  68,   8,  28,  62, acGUI_Font120_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{  78,  68,   8,  28,  93, acGUI_Font120_004D } /* code 004D, LATIN CAPITAL LETTER M */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font120_Prop5 = {
   0x004D /* first character */
  ,0x004D /* last character  */
  ,&GUI_Font120_CharInfo[  6] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font120_Prop4 = {
   0x0041 /* first character */
  ,0x0042 /* last character  */
  ,&GUI_Font120_CharInfo[  4] /* address of first character */
  ,&GUI_Font120_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font120_Prop3 = {
   0x0038 /* first character */
  ,0x0038 /* last character  */
  ,&GUI_Font120_CharInfo[  3] /* address of first character */
  ,&GUI_Font120_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font120_Prop2 = {
   0x0031 /* first character */
  ,0x0032 /* last character  */
  ,&GUI_Font120_CharInfo[  1] /* address of first character */
  ,&GUI_Font120_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font120_Prop1 = {
   0x002D /* first character */
  ,0x002D /* last character  */
  ,&GUI_Font120_CharInfo[  0] /* address of first character */
  ,&GUI_Font120_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font120 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,120 /* height of font  */
  ,120 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Font120_Prop1}
  ,96 /* Baseline */
  ,51 /* Height of lowercase characters */
  ,68 /* Height of capital characters */
};

