/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: 16.c                                                  *
* Font:        ????z?                                              *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 16                                            *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: K:\?????????\font\16.txt                     *
*                                                                    *
**********************************************************************
*/

#include "16.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/

/* Start of unicode area <CJK Unified Ideographs> */
extern GUI_CONST_STORAGE GUI_FONT GUI_Font16;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Font16_5411[ 32] = { /* code 5411 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____X___,________,
  _XXXXXXX,X_______,
  _X______,X_______,
  _X_XXXX_,X_______,
  _X_X__X_,X_______,
  _X_X__X_,X_______,
  _X_XXXX_,X_______,
  _X_X____,X_______,
  _X____XX,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_672C[ 32] = { /* code 672C */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  XXXXXXXX,XX______,
  ____XX__,________,
  ___X_XX_,________,
  ___X_X_X,________,
  __X__X_X,________,
  _X___X__,X_______,
  X_XXXXXX,_X______,
  _____X__,________,
  _____X__,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_79BB[ 32] = { /* code 79BB */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XX__,________,
  XXXXXXXX,XX______,
  __XXX_XX,X_______,
  __XXXXXX,X_______,
  __XXXXXX,X_______,
  _____X__,________,
  _XXXXXXX,X_______,
  _X_X__X_,X_______,
  _X_XXXXX,X_______,
  _X_____X,X_______,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_822A[ 32] = { /* code 822A */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X___XX,________,
  _XXXXXXX,XX______,
  _XXX____,________,
  _X_X____,________,
  XXXX_XXX,X_______,
  _X_X_X__,X_______,
  _XXX_X__,X_______,
  _XXX_X__,XX______,
  XX_X_X__,XX______,
  X_XXX___,XX______,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_8239[ 32] = { /* code 8239 */
  ________,________,
  ________,________,
  ________,________,
  __X_____,________,
  _XXX_XXX,________,
  _XXX_X_X,________,
  _XXX_X_X,________,
  _XXXX__X,XX______,
  XXXX____,________,
  _X_X_XXX,X_______,
  _XXX_X__,X_______,
  _X_X_XXX,X_______,
  X_XX_X__,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_8DDD[ 32] = { /* code 8DDD */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXX_XXX,XX______,
  _X_X_X__,________,
  _XXX_X__,________,
  _XX__XXX,XX______,
  __X__X__,_X______,
  _XXX_XXX,XX______,
  _XX__X__,________,
  _XXX_X__,________,
  XX___XXX,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_901F[ 32] = { /* code 901F */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X____X_,________,
  __XXXXXX,XX______,
  ____XXXX,X_______,
  _XX_X_X_,X_______,
  __X_XXXX,X_______,
  __X_XXX_,X_______,
  __X_X_XX,X_______,
  _XXX__X_,_X______,
  _X_XXXXX,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Font16_CharInfo[7] = {
   {  10,  10,  2, acGUI_Font16_5411 } /* code 5411 */
  ,{  10,  10,  2, acGUI_Font16_672C } /* code 672C */
  ,{  10,  10,  2, acGUI_Font16_79BB } /* code 79BB */
  ,{  10,  10,  2, acGUI_Font16_822A } /* code 822A */
  ,{  10,  10,  2, acGUI_Font16_8239 } /* code 8239 */
  ,{  10,  10,  2, acGUI_Font16_8DDD } /* code 8DDD */
  ,{  10,  10,  2, acGUI_Font16_901F } /* code 901F */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop7 = {
   0x901F /* first character */
  ,0x901F /* last character  */
  ,&GUI_Font16_CharInfo[  6] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop6 = {
   0x8DDD /* first character */
  ,0x8DDD /* last character  */
  ,&GUI_Font16_CharInfo[  5] /* address of first character */
  ,&GUI_Font16_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop5 = {
   0x8239 /* first character */
  ,0x8239 /* last character  */
  ,&GUI_Font16_CharInfo[  4] /* address of first character */
  ,&GUI_Font16_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop4 = {
   0x822A /* first character */
  ,0x822A /* last character  */
  ,&GUI_Font16_CharInfo[  3] /* address of first character */
  ,&GUI_Font16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop3 = {
   0x79BB /* first character */
  ,0x79BB /* last character  */
  ,&GUI_Font16_CharInfo[  2] /* address of first character */
  ,&GUI_Font16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop2 = {
   0x672C /* first character */
  ,0x672C /* last character  */
  ,&GUI_Font16_CharInfo[  1] /* address of first character */
  ,&GUI_Font16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop1 = {
   0x5411 /* first character */
  ,0x5411 /* last character  */
  ,&GUI_Font16_CharInfo[  0] /* address of first character */
  ,&GUI_Font16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Font16_Prop1}
  ,12 /* Baseline */
  ,5 /* Height of lowercase characters */
  ,8 /* Height of capital characters */
};

