#ifndef _28_H
#define _28_H

#include "GUI.h"

extern GUI_CONST_STORAGE GUI_FONT GUI_Font24;
extern GUI_CONST_STORAGE GUI_FONT GUI_Font28;
extern GUI_CONST_STORAGE GUI_FONT GUI_Font281;
extern GUI_CONST_STORAGE GUI_FONT GUI_Font29;
extern GUI_CONST_STORAGE GUI_FONT GUI_Font30;

extern GUI_CONST_STORAGE GUI_FONT GUI_Font50;
#endif


