/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.24                          *
*        Compiled Jan 27 2014, 11:28:24                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "MainTask.h"

#include "Config.h"
#include "Setting.h"
#include "SystemConfig.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0      (GUI_ID_USER + 0x00)
#define ID_BUTTON_OK     (GUI_ID_USER + 0x01)
#define ID_BUTTON_CANCEL (GUI_ID_USER + 0x02)
#define ID_TEXT_CONTENT  (GUI_ID_USER + 0x03)


/*------------------------- external variables -------------------------*/
extern short N_monitedBoat;
extern WM_HWIN menuWin;
extern WM_HWIN subWins[4];
extern WM_HWIN confirmWin;
extern MNT_SETTING mntSetting;

extern SIMP_BERTH Simp_Berthes[BOAT_LIST_SIZE_MAX];

/*------------------------- external functions -------------------------*/
//extern int MNT_deleteByIndex(MNT_BOAT * pMNT_Boat,int index, long id);
extern int MNT_deleteById(MNT_BOAT * pMNT_Boat, long id);



/*------------------------- local variables ----------------------------*/
static WM_HWIN dlgFrame;
static WM_HWIN dlgTextContent;
static WM_HWIN dlgBtOk;
static WM_HWIN dlgBtCancel;
static int userMsgChoose  = 0;
static WM_HWIN myHWinSrc;
static long ReceivedDatas[3] = {0};
static int Option  = 0;
static WM_MESSAGE myMsg;

/*------------------------- local functions -----------------------------*/
void mySB(WM_MESSAGE * pMsg);
//extern void mntSetting_init(void);
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Win_Confirm", ID_WINDOW_0,      200,  120,  400,  200,   0, 0x64, 0 },
  { BUTTON_CreateIndirect, "OK",          ID_BUTTON_OK,      60,  110,   80,  40,    0, 0x0,  0 },
  { BUTTON_CreateIndirect, "Cancel",      ID_BUTTON_CANCEL, 260,  110,   80,  40,    0, 0x0,  0 },
  { TEXT_CreateIndirect, "Text",          ID_TEXT_CONTENT,   0,   40,  400, 40, TEXT_CF_HCENTER, 0x0,  0 }
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

//const CnfmWin_COLOR CnfmWinSkins[2]  = {

//                                        };

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	
	const WM_KEY_INFO* pInfo;
  WM_HWIN thisFrame  = pMsg->hWin;

  int     NCode;
  int     Id;
  int i  = 0;
  // USER START (Optionally insert additional variables)
  // USER END
//INFO("MsgId:%d",pMsg->MsgId);  
  switch (pMsg->MsgId) {
  case USER_MSG_SKIN:
       if(pMsg->Data.v == SKIN_Night)    
          WINDOW_SetBkColor(pMsg->hWin, GUI_DARKGRAY); 
       else
          WINDOW_SetBkColor(pMsg->hWin, GUI_WHITE);
       break;  
	
  case WM_INIT_DIALOG:
       
    //
    // Initialization of 'bt_OK'
    //
    dlgBtOk = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_OK);
//    WM_SetCallback(dlgBtOk, &mySB);
    BUTTON_SetText(dlgBtOk, "确定");
	   BUTTON_SetFont(dlgBtOk, &GUI_Font28);
    //
    // Initialization of 'bt_Cancle'
    //
    dlgBtCancel = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
    BUTTON_SetText(dlgBtCancel, "取消");
	   BUTTON_SetFont(dlgBtCancel, &GUI_Font28);
    //
    // Initialization of 'Text'
    //
     dlgTextContent = WM_GetDialogItem(pMsg->hWin, ID_TEXT_CONTENT);
     //TEXT_SetText(dlgTextContent, "");
     TEXT_SetFont(dlgTextContent, &GUI_Font28);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
	
	case WM_KEY:
		pInfo  = (WM_KEY_INFO*)pMsg->Data.p;
	
	  switch(pInfo->Key)
		{
			case GUI_KEY_LEFT:
			case GUI_KEY_RIGHT:
				GUI_StoreKeyMsg(GUI_KEY_TAB,1);
			break;
//   case GUI_KEY_ENTER:
//INFO("case enter");   
//        break;
			
			default:
				break;
		}
		break;
		
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);    // Id of widget
    NCode = pMsg->Data.v;               // Notification code
    switch (NCode) {
    case GUI_KEY_BACKSPACE:    
         break;
    case WM_NOTIFICATION_RELEASED:      // React only if released
      switch (Id) {
      case ID_BUTTON_OK:
           myMsg.hWin     = myMsg.hWinSrc;
           myMsg.hWinSrc  = pMsg->hWin;
           myMsg.MsgId    = USER_MSG_ID_REPLY;
           myMsg.Data.v   = REPLY_OK;
           WM_SendMessage(myMsg.hWin, &myMsg);
           break;
      case ID_BUTTON_CANCEL:
           WM_SetFocusOnPrevChild(confirmWin);
           
           myMsg.hWin     = myMsg.hWinSrc;
           myMsg.hWinSrc  = pMsg->hWin;
           myMsg.MsgId    = USER_MSG_ID_REPLY;
           myMsg.Data.v   = REPLY_CANCEL;
           WM_SendMessage(myMsg.hWin, &myMsg);
           break;
      }
      WM_BringToBottom(pMsg->hWin);
      break;
    }
    break;
  // USER START (Optionally insert additional message handling)
  case USER_MSG_ID_CHOOSE:
      Option  = pMsg->Data.v;
      
      myMsg.hWinSrc  = pMsg->hWinSrc;
      myMsg.Data.v   = Option;
      
      switch(Option)   
      {
         case CANCEL_MONITED:         
              TEXT_SetText(dlgTextContent, "确认取消监控该船舶？");
              break;
          
         case STORE_SETTING:       
              TEXT_SetText(dlgTextContent, "确认保存监控设置项？");         
              break;
         case ADD_MONITED:             
              TEXT_SetText(dlgTextContent, "确认添加网位仪监控列表？");
              break;
         case SYS_SETTING:
              TEXT_SetText(dlgTextContent, "确认保存设置内容？");
         break;
         
         default:
INFO("Something error!");         
              break;
      }
      break;
   break;
//   case USER_MSG_ID_CHOOSE:
//        
//        break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFrm_Confirm
*/
WM_HWIN confirmWinCreate(void);
WM_HWIN confirmWinCreate(void) {
  WM_HWIN hWin;
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
//  res = GUI_ExecDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END






/*************************** End of file ****************************/


