/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.24                          *
*        Compiled Jan 27 2014, 11:28:24                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "MainTask.h"

#include "Config.h"
#include "Setting.h"
#include "sysConf.h"
#include "skinColor.h"
#include "dlg.h"
#include "28.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0      (GUI_ID_USER + 0x00)
#define ID_BUTTON_OK     (GUI_ID_USER + 0x01)
#define ID_BUTTON_CANCEL (GUI_ID_USER + 0x02)
#define ID_TEXT_CONTENT  (GUI_ID_USER + 0x03)

/*------------------------- Global variables ---------------------------*/
WM_HWIN confirmWin;



/*------------------------- external variables -------------------------*/
extern SIMP_BERTH Simp_Berthes[BOAT_NUM_MAX];




/*------------------------- local variables ----------------------------*/

static WM_HWIN dlgTextContent;

static int Option  = 0;
static WM_MESSAGE myMsg;
static WM_HWIN Confim_BUTTON[2];

static void myButton(WM_MESSAGE * pMsg);



/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
//static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
//  { WINDOW_CreateIndirect, "Win_Confirm", GUI_ID_BUTTON2,      200,  120,  400,  200,  0, 0x64,0  },
//  { BUTTON_CreateIndirect, "OK",          GUI_ID_BUTTON0,      60,  110,   80,  40,    0, 0x0,  0 },
//  { BUTTON_CreateIndirect, "Cancel",      GUI_ID_BUTTON1, 260,  110,   80,  40,    0, 0x0,  0 },
//  { TEXT_CreateIndirect, "Text",          ID_TEXT_CONTENT,   0,   40,  400, 40, TEXT_CF_HCENTER, 0x0,  0 }
//  // USER START (Optionally insert additional widgets)
//  // USER END
//};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

static const CnfmWin_COLOR * pSkin  = cnfmWinSkins;
//const CnfmWin_COLOR CnfmWinSkins[2]  = {

//                                        };

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	
	const WM_KEY_INFO* pInfo;
  WM_HWIN thisFrame  = pMsg->hWin;

  int     NCode;
  int     Id;
	
	int xSize;
	int ySize;
  // USER START (Optionally insert additional variables)
  // USER END
//INFO("MsgId:%d",pMsg->MsgId);  
  switch (pMsg->MsgId) {
		
  case WM_PAINT:
       xSize = WM_GetWindowSizeX(pMsg->hWin);
       ySize = WM_GetWindowSizeY(pMsg->hWin);
       GUI_DrawGradientRoundedV(0, 0, xSize - 1, ySize - 1, 20, pSkin->bkTop,pSkin->bkBottom);
       break;
	
	case USER_MSG_SKIN:
      pSkin = &(cnfmWinSkins[pMsg->Data.v]);
    
      BUTTON_SetBkColor(Confim_BUTTON[0], BUTTON_BI_UNPRESSED, pSkin->bt_bkColor);
      BUTTON_SetBkColor(Confim_BUTTON[1], BUTTON_BI_UNPRESSED, pSkin->bt_bkColor);
      
      TEXT_SetTextColor(dlgTextContent, pSkin->text);
      break;
 
	//WM_INIT_DIALOG:
  case WM_CREATE:
    //
    // Initialization of 'bt_OK'
    //
      BUTTON_CreateEx (60,110,80,40,thisFrame, WM_CF_HASTRANS  ,0,GUI_ID_BUTTON0);
      Confim_BUTTON[0] = WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON0);
      WM_ShowWindow (Confim_BUTTON[0]);
      BUTTON_SetText(Confim_BUTTON[0], "确定");
      BUTTON_SetFont(Confim_BUTTON[0], &GUI_Font30);
      BUTTON_SetBkColor(Confim_BUTTON[0],BUTTON_BI_UNPRESSED,pSkin->bt_bkColor);
      BUTTON_SetTextColor(Confim_BUTTON[0],BUTTON_BI_UNPRESSED,pSkin->bt_txColor);
      WM_SetCallback(Confim_BUTTON[0], &myButton);
        //
        // Initialization of 'bt_Cancle'
        //
      BUTTON_CreateEx(260,  110,   80,  40,thisFrame,WM_CF_HASTRANS,0,GUI_ID_BUTTON1);
      Confim_BUTTON[1] = WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON1);
      WM_ShowWindow (Confim_BUTTON[1]);
      BUTTON_SetText(Confim_BUTTON[1], "取消");
      BUTTON_SetFont(Confim_BUTTON[1], &GUI_Font30);
      BUTTON_SetBkColor(Confim_BUTTON[1],BUTTON_BI_UNPRESSED,pSkin->bt_bkColor);
      BUTTON_SetTextColor(Confim_BUTTON[1],BUTTON_BI_UNPRESSED,pSkin->bt_txColor);
      WM_SetCallback(Confim_BUTTON[1], &myButton);
    //
    // Initialization of 'Text'
    //
		    TEXT_CreateEx (0,   40,  400, 40, thisFrame,WM_CF_SHOW,0,ID_TEXT_CONTENT,NULL);
      dlgTextContent = WM_GetDialogItem(pMsg->hWin, ID_TEXT_CONTENT);
		    TEXT_SetTextColor (dlgTextContent,pSkin->text);
		    TEXT_SetTextAlign(dlgTextContent,TEXT_CF_HCENTER);
     //TEXT_SetText(dlgTextContent, "");
      TEXT_SetFont(dlgTextContent, &GUI_Font30);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
      break;
	
	case WM_KEY:

		pInfo  = (WM_KEY_INFO*)pMsg->Data.p;
	
	  switch(pInfo->Key)
		 {
		   	case GUI_KEY_LEFT:
		   	case GUI_KEY_RIGHT: 				
           if(WM_HasFocus(WM_GetDialogItem(thisFrame,GUI_ID_BUTTON0)))
           {
              WM_SetFocus (WM_GetDialogItem(thisFrame,GUI_ID_BUTTON1));
            }
           else
           {
              WM_SetFocus (WM_GetDialogItem(thisFrame,GUI_ID_BUTTON0));
           }
			        break;	
       
      case GUI_KEY_BACKSPACE:
           {
              myMsg.hWin  = myMsg.hWinSrc;
              myMsg.hWinSrc  = pMsg->hWin;
              myMsg.MsgId    = USER_MSG_REPLY;
              myMsg.Data.v   = REPLY_CANCEL;
              WM_SendMessage(myMsg.hWin, &myMsg);  
              WM_BringToBottom(confirmWin);
           }
           break;  
           
			   default:
			       	break;
		}
		break;
		
  case WM_NOTIFY_PARENT:
       Id    = WM_GetId(pMsg->hWinSrc);    // Id of widget
       NCode = pMsg->Data.v;               // Notification code
       switch (NCode) 
       {

          case WM_NOTIFICATION_RELEASED:      // React only if released
               switch (Id) 
               {
                  case GUI_ID_BUTTON0: 
                       myMsg.hWin     = myMsg.hWinSrc;
                       myMsg.hWinSrc  = pMsg->hWin;
                       myMsg.MsgId    = USER_MSG_REPLY;
                       myMsg.Data.v   = REPLY_OK;
                       WM_SendMessage(myMsg.hWin, &myMsg);
                       break;
                       
                  case GUI_ID_BUTTON1:
                       WM_SetFocusOnPrevChild(confirmWin);
                       
                       myMsg.hWin     = myMsg.hWinSrc;
                       myMsg.hWinSrc  = pMsg->hWin;
                       myMsg.MsgId    = USER_MSG_REPLY;
                       myMsg.Data.v   = REPLY_CANCEL;
                       WM_SendMessage(myMsg.hWin, &myMsg);
                       break;
               }
               WM_BringToBottom(confirmWin);
               break;
    }
    break;
  // USER START (Optionally insert additional message handling)
  case USER_MSG_CHOOSE:
      Option  = pMsg->Data.v;
      
      myMsg.hWinSrc  = pMsg->hWinSrc;
      myMsg.Data.v   = Option;
      
      switch(Option)   
      {
         case CANCEL_MONITED:         
              TEXT_SetText(dlgTextContent, "确认取消监控该船舶？");
              break;
          
         case STORE_SETTING:       
              TEXT_SetText(dlgTextContent, "确认保存监控设置项？");    
              break;
         case ADD_MONITED:             
              TEXT_SetText(dlgTextContent, "确认添加网位仪监控列表？");
              break;
         case SYS_SETTING:
              TEXT_SetText(dlgTextContent, "确认保存设置内容？");
							       break;
         case SYS_REVIVE:
              TEXT_SetText(dlgTextContent, "确认恢复出厂设置？");
              break;
         
         default:       
              break;
      }
      break;
//   case USER_MSG_CHOOSE:
//        
//        break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFrm_Confirm
*/
WM_HWIN confirmWinCreate(void) {
  WM_HWIN hWin;
	
  //hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
			//hWin  =		GUI_ExecDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
		
	hWin = WM_CreateWindow(200, 120, 400, 200,WM_CF_SHOW, _cbDialog, 0);
	//  res = GUI_ExecDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	WM_SetHasTrans(hWin);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END


static void myButton (WM_MESSAGE *pMsg)
{
 	int index = 0;



	 switch(pMsg->MsgId)   
  { 	 
     case WM_SET_FOCUS:
          index  = WM_GetId(pMsg->hWin) - GUI_ID_BUTTON0;
           
          if(pMsg->Data.v == 0)
          {
             BUTTON_SetBkColor(Confim_BUTTON[index], BUTTON_CI_UNPRESSED, pSkin->bt_bkColor);
             //TEXT_SetBkColor(Texts[index], pSkin->MntSetWin_bkNOFOCUS);
          }
          else
          {
            BUTTON_SetBkColor(Confim_BUTTON[index], BUTTON_CI_UNPRESSED, pSkin->bt_bkFocus);
            //TEXT_SetBkColor(Texts[index], GUI_DARKMAGENTA); 
          }
          
          BUTTON_Callback(pMsg);
          break;

			default:
			      	BUTTON_Callback(pMsg);
			       break;
	}
}

/*************************** End of file ****************************/


