/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V5.26.            *
*        Compiled Aug  8 2014, 14:05:55                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: fish                                                  *
* Dimensions:  46 * 19                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmfish;

static GUI_CONST_STORAGE unsigned char _acfish[] = {
  /* RLE: 049 Pixels @ 000,000 */ 49, 0xFF, 
  /* RLE: 001 Pixels @ 003,001 */ 1, 0xFB, 
  /* RLE: 044 Pixels @ 004,001 */ 44, 0xFF, 
  /* ABS: 002 Pixels @ 002,002 */ 0, 2, 0xA5, 0x70, 
  /* RLE: 014 Pixels @ 004,002 */ 14, 0xFF, 
  /* ABS: 014 Pixels @ 018,002 */ 0, 14, 0xA5, 0x74, 0x4D, 0x46, 0x4B, 0x48, 0x46, 0x46, 0x4D, 0x46, 0x46, 0x5A, 0x6D, 0x9D, 
  /* RLE: 016 Pixels @ 032,002 */ 16, 0xFF, 
  /* ABS: 003 Pixels @ 002,003 */ 0, 3, 0x86, 0x4B, 0xFE, 
  /* RLE: 010 Pixels @ 005,003 */ 10, 0xFF, 
  /* ABS: 020 Pixels @ 015,003 */ 0, 20, 0x9B, 0x65, 0x46, 0x48, 0x50, 0x6B, 0x90, 0xC8, 0xF4, 0xFF, 0xFF, 0xF9, 0xBC, 0x93, 0x5F, 0x58, 0x4B, 0x48, 0x5A, 0xA5, 
  /* RLE: 014 Pixels @ 035,003 */ 14, 0xFF, 
  /* ABS: 002 Pixels @ 003,004 */ 0, 2, 0x58, 0x6B, 
  /* RLE: 008 Pixels @ 005,004 */ 8, 0xFF, 
  /* ABS: 005 Pixels @ 013,004 */ 0, 5, 0x83, 0x50, 0x4D, 0x58, 0x9D, 
  /* RLE: 012 Pixels @ 018,004 */ 12, 0xFF, 
  /* ABS: 007 Pixels @ 030,004 */ 0, 7, 0xFA, 0x00, 0x00, 0x00, 0x48, 0x4D, 0x83, 
  /* RLE: 012 Pixels @ 037,004 */ 12, 0xFF, 
  /* ABS: 003 Pixels @ 003,005 */ 0, 3, 0x9D, 0x4B, 0xCD, 
  /* RLE: 005 Pixels @ 006,005 */ 5, 0xFF, 
  /* ABS: 005 Pixels @ 011,005 */ 0, 5, 0xA7, 0x52, 0x4D, 0x71, 0xFB, 
  /* RLE: 014 Pixels @ 016,005 */ 14, 0xFF, 
  /* ABS: 009 Pixels @ 030,005 */ 0, 9, 0xFD, 0x00, 0x00, 0xF8, 0xF6, 0x74, 0x46, 0x50, 0xC8, 
  /* RLE: 011 Pixels @ 039,005 */ 11, 0xFF, 
  /* ABS: 002 Pixels @ 004,006 */ 0, 2, 0x6B, 0x52, 
  /* RLE: 004 Pixels @ 006,006 */ 4, 0xFF, 
  /* ABS: 004 Pixels @ 010,006 */ 0, 4, 0x6B, 0x4B, 0x6B, 0xFD, 
  /* RLE: 016 Pixels @ 014,006 */ 16, 0xFF, 
  /* ABS: 010 Pixels @ 030,006 */ 0, 10, 0xFB, 0x00, 0x00, 0xFB, 0xFF, 0xFF, 0xFD, 0x75, 0x46, 0x71, 
  /* RLE: 011 Pixels @ 040,006 */ 11, 0xFF, 
  /* ABS: 007 Pixels @ 005,007 */ 0, 7, 0x5D, 0x6D, 0xFF, 0xE9, 0x5A, 0x48, 0xD1, 
  /* RLE: 018 Pixels @ 012,007 */ 18, 0xFF, 
  /* ABS: 004 Pixels @ 030,007 */ 0, 4, 0xFD, 0x00, 0x00, 0xFE, 
  /* RLE: 004 Pixels @ 034,007 */ 4, 0xFF, 
  /* ABS: 004 Pixels @ 038,007 */ 0, 4, 0xCD, 0x4D, 0x55, 0xE4, 
  /* RLE: 009 Pixels @ 042,007 */ 9, 0xFF, 
  /* ABS: 005 Pixels @ 005,008 */ 0, 5, 0xDE, 0x4B, 0x5D, 0x4B, 0x6D, 
  /* RLE: 020 Pixels @ 010,008 */ 20, 0xFF, 
  /* ABS: 013 Pixels @ 030,008 */ 0, 13, 0xFD, 0x00, 0x00, 0xFA, 0xFF, 0xD4, 0x5A, 0xD1, 0xFF, 0xFF, 0x68, 0x46, 0x8E, 
  /* RLE: 009 Pixels @ 043,008 */ 9, 0xFF, 
  /* ABS: 003 Pixels @ 006,009 */ 0, 3, 0x83, 0x00, 0x50, 
  /* RLE: 021 Pixels @ 009,009 */ 21, 0xFF, 
  /* ABS: 014 Pixels @ 030,009 */ 0, 14, 0xFB, 0x00, 0x00, 0xFA, 0xFF, 0x5A, 0x00, 0x55, 0xFF, 0xFF, 0xFF, 0x52, 0x46, 0x8E, 
  /* RLE: 007 Pixels @ 044,009 */ 7, 0xFF, 
  /* ABS: 005 Pixels @ 005,010 */ 0, 5, 0xD0, 0x4D, 0x63, 0x55, 0x60, 
  /* RLE: 020 Pixels @ 010,010 */ 20, 0xFF, 
  /* ABS: 014 Pixels @ 030,010 */ 0, 14, 0xFA, 0x00, 0x00, 0xFB, 0xFF, 0xD0, 0x5A, 0xCB, 0xFF, 0xFF, 0x65, 0x50, 0xAE, 0xE9, 
  /* RLE: 007 Pixels @ 044,010 */ 7, 0xFF, 
  /* ABS: 007 Pixels @ 005,011 */ 0, 7, 0x55, 0x6D, 0xFF, 0xE9, 0x58, 0x4D, 0xD0, 
  /* RLE: 018 Pixels @ 012,011 */ 18, 0xFF, 
  /* ABS: 004 Pixels @ 030,011 */ 0, 4, 0xFD, 0x00, 0x00, 0xFD, 
  /* RLE: 004 Pixels @ 034,011 */ 4, 0xFF, 
  /* ABS: 004 Pixels @ 038,011 */ 0, 4, 0xD4, 0x4B, 0x58, 0xE7, 
  /* RLE: 008 Pixels @ 042,011 */ 8, 0xFF, 
  /* ABS: 002 Pixels @ 004,012 */ 0, 2, 0x6D, 0x4D, 
  /* RLE: 004 Pixels @ 006,012 */ 4, 0xFF, 
  /* ABS: 003 Pixels @ 010,012 */ 0, 3, 0x6B, 0x48, 0x68, 
  /* RLE: 017 Pixels @ 013,012 */ 17, 0xFF, 
  /* ABS: 010 Pixels @ 030,012 */ 0, 10, 0xFD, 0x00, 0x00, 0xFD, 0xFF, 0xFF, 0xF8, 0x71, 0x43, 0x6D, 
  /* RLE: 009 Pixels @ 040,012 */ 9, 0xFF, 
  /* ABS: 003 Pixels @ 003,013 */ 0, 3, 0xA7, 0x4D, 0xD4, 
  /* RLE: 005 Pixels @ 006,013 */ 5, 0xFF, 
  /* ABS: 005 Pixels @ 011,013 */ 0, 5, 0xA7, 0x50, 0x4B, 0x71, 0xFB, 
  /* RLE: 014 Pixels @ 016,013 */ 14, 0xFF, 
  /* ABS: 009 Pixels @ 030,013 */ 0, 9, 0xFE, 0x00, 0x00, 0xFD, 0xF2, 0x7C, 0x48, 0x5A, 0xC3, 
  /* RLE: 010 Pixels @ 039,013 */ 10, 0xFF, 
  /* ABS: 002 Pixels @ 003,014 */ 0, 2, 0x50, 0x70, 
  /* RLE: 008 Pixels @ 005,014 */ 8, 0xFF, 
  /* ABS: 005 Pixels @ 013,014 */ 0, 5, 0x93, 0x50, 0x48, 0x5A, 0xA0, 
  /* RLE: 012 Pixels @ 018,014 */ 12, 0xFF, 
  /* ABS: 007 Pixels @ 030,014 */ 0, 7, 0xFC, 0x00, 0x01, 0x00, 0x43, 0x50, 0x81, 
  /* RLE: 011 Pixels @ 037,014 */ 11, 0xFF, 
  /* ABS: 003 Pixels @ 002,015 */ 0, 3, 0x89, 0x4B, 0xFE, 
  /* RLE: 010 Pixels @ 005,015 */ 10, 0xFF, 
  /* ABS: 020 Pixels @ 015,015 */ 0, 20, 0xA0, 0x55, 0x4B, 0x46, 0x50, 0x68, 0x90, 0xC3, 0xF2, 0xFF, 0xFF, 0xF5, 0xC3, 0x89, 0x65, 0x52, 0x48, 0x40, 0x63, 0x9D, 
  /* RLE: 013 Pixels @ 035,015 */ 13, 0xFF, 
  /* ABS: 002 Pixels @ 002,016 */ 0, 2, 0x4D, 0x70, 
  /* RLE: 014 Pixels @ 004,016 */ 14, 0xFF, 
  /* ABS: 014 Pixels @ 018,016 */ 0, 14, 0xA5, 0x71, 0x4B, 0x46, 0x50, 0x48, 0x46, 0x4B, 0x4D, 0x46, 0x48, 0x5D, 0x6D, 0xA0, 
  /* RLE: 015 Pixels @ 032,016 */ 15, 0xFF, 
  /* ABS: 003 Pixels @ 001,017 */ 0, 3, 0xE5, 0xE1, 0xFC, 
  /* RLE: 088 Pixels @ 004,017 */ 88, 0xFF, 
  0
};  // 420 bytes for 874 pixels

GUI_CONST_STORAGE GUI_BITMAP bmfish = {
  46, // xSize
  19, // ySize
  46, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acfish,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
