/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V5.26.            *
*        Compiled Aug  8 2014, 14:05:55                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: mao                                                   *
* Dimensions:  39 * 39                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmmao;

static GUI_CONST_STORAGE unsigned char _acmao[] = {
  /* RLE: 016 Pixels @ 000,000 */ 16, 0xFF, 
  /* ABS: 008 Pixels @ 016,000 */ 0, 8, 0xFD, 0x68, 0x1C, 0x02, 0x02, 0x1C, 0x68, 0xFD, 
  /* RLE: 030 Pixels @ 024,000 */ 30, 0xFF, 
  /* ABS: 010 Pixels @ 015,001 */ 0, 10, 0xFD, 0x3F, 0x21, 0x73, 0xCF, 0xCF, 0x73, 0x21, 0x3F, 0xFD, 
  /* RLE: 029 Pixels @ 025,001 */ 29, 0xFF, 
  /* ABS: 002 Pixels @ 015,002 */ 0, 2, 0x68, 0x21, 
  /* RLE: 006 Pixels @ 017,002 */ 6, 0xFF, 
  /* ABS: 002 Pixels @ 023,002 */ 0, 2, 0x21, 0x68, 
  /* RLE: 029 Pixels @ 025,002 */ 29, 0xFF, 
  /* ABS: 002 Pixels @ 015,003 */ 0, 2, 0x1C, 0x73, 
  /* RLE: 006 Pixels @ 017,003 */ 6, 0xFF, 
  /* ABS: 002 Pixels @ 023,003 */ 0, 2, 0x73, 0x1C, 
  /* RLE: 029 Pixels @ 025,003 */ 29, 0xFF, 
  /* ABS: 002 Pixels @ 015,004 */ 0, 2, 0x02, 0xCF, 
  /* RLE: 006 Pixels @ 017,004 */ 6, 0xFF, 
  /* ABS: 002 Pixels @ 023,004 */ 0, 2, 0xCF, 0x02, 
  /* RLE: 029 Pixels @ 025,004 */ 29, 0xFF, 
  /* ABS: 002 Pixels @ 015,005 */ 0, 2, 0x02, 0xCF, 
  /* RLE: 006 Pixels @ 017,005 */ 6, 0xFF, 
  /* ABS: 002 Pixels @ 023,005 */ 0, 2, 0xCF, 0x02, 
  /* RLE: 029 Pixels @ 025,005 */ 29, 0xFF, 
  /* ABS: 002 Pixels @ 015,006 */ 0, 2, 0x1C, 0x73, 
  /* RLE: 006 Pixels @ 017,006 */ 6, 0xFF, 
  /* ABS: 002 Pixels @ 023,006 */ 0, 2, 0x73, 0x1C, 
  /* RLE: 029 Pixels @ 025,006 */ 29, 0xFF, 
  /* ABS: 002 Pixels @ 015,007 */ 0, 2, 0x68, 0x21, 
  /* RLE: 006 Pixels @ 017,007 */ 6, 0xFF, 
  /* ABS: 002 Pixels @ 023,007 */ 0, 2, 0x21, 0x68, 
  /* RLE: 029 Pixels @ 025,007 */ 29, 0xFF, 
  /* ABS: 010 Pixels @ 015,008 */ 0, 10, 0xFD, 0x3F, 0x21, 0x73, 0xCF, 0xCF, 0x73, 0x21, 0x3F, 0xFD, 
  /* RLE: 030 Pixels @ 025,008 */ 30, 0xFF, 
  /* ABS: 008 Pixels @ 016,009 */ 0, 8, 0xFD, 0x68, 0x1C, 0x01, 0x01, 0x1C, 0x68, 0xFD, 
  /* RLE: 034 Pixels @ 024,009 */ 34, 0xFF, 
  /* ABS: 002 Pixels @ 019,010 */ 0, 2, 0x52, 0x52, 
  /* RLE: 037 Pixels @ 021,010 */ 37, 0xFF, 
  /* ABS: 002 Pixels @ 019,011 */ 0, 2, 0x52, 0x51, 
  /* RLE: 037 Pixels @ 021,011 */ 37, 0xFF, 
  /* ABS: 002 Pixels @ 019,012 */ 0, 2, 0x51, 0x51, 
  /* RLE: 037 Pixels @ 021,012 */ 37, 0xFF, 
  /* ABS: 002 Pixels @ 019,013 */ 0, 2, 0x52, 0x51, 
  /* RLE: 037 Pixels @ 021,013 */ 37, 0xFF, 
  /* ABS: 002 Pixels @ 019,014 */ 0, 2, 0x51, 0x52, 
  /* RLE: 037 Pixels @ 021,014 */ 37, 0xFF, 
  /* ABS: 002 Pixels @ 019,015 */ 0, 2, 0x52, 0x52, 
  /* RLE: 037 Pixels @ 021,015 */ 37, 0xFF, 
  /* ABS: 002 Pixels @ 019,016 */ 0, 2, 0x51, 0x51, 
  /* RLE: 037 Pixels @ 021,016 */ 37, 0xFF, 
  /* ABS: 002 Pixels @ 019,017 */ 0, 2, 0x51, 0x52, 
  /* RLE: 026 Pixels @ 021,017 */ 26, 0xFF, 
  /* ABS: 026 Pixels @ 008,018 */ 0, 26, 0x91, 0x52, 0x52, 0x51, 0x51, 0x52, 0x52, 0x52, 0x51, 0x52, 0x52, 0x1A, 0x1A, 0x52, 0x52, 0x51, 0x51, 0x52, 0x51, 0x51, 0x52, 0x52, 0x52, 0x51, 0x51, 0x91, 
  /* RLE: 013 Pixels @ 034,018 */ 13, 0xFF, 
  /* ABS: 007 Pixels @ 008,019 */ 0, 7, 0x91, 0x52, 0x52, 0x52, 0x51, 0x52, 0x52, 
  /* RLE: 004 Pixels @ 015,019 */ 4, 0x51, 
  /* ABS: 015 Pixels @ 019,019 */ 0, 15, 0x1A, 0x1A, 0x52, 0x52, 0x51, 0x52, 0x52, 0x51, 0x51, 0x52, 0x51, 0x51, 0x52, 0x52, 0x91, 
  /* RLE: 024 Pixels @ 034,019 */ 24, 0xFF, 
  /* ABS: 002 Pixels @ 019,020 */ 0, 2, 0x52, 0x52, 
  /* RLE: 037 Pixels @ 021,020 */ 37, 0xFF, 
  /* ABS: 002 Pixels @ 019,021 */ 0, 2, 0x51, 0x51, 
  /* RLE: 037 Pixels @ 021,021 */ 37, 0xFF, 
  /* ABS: 002 Pixels @ 019,022 */ 0, 2, 0x51, 0x51, 
  /* RLE: 037 Pixels @ 021,022 */ 37, 0xFF, 
  /* ABS: 002 Pixels @ 019,023 */ 0, 2, 0x51, 0x51, 
  /* RLE: 037 Pixels @ 021,023 */ 37, 0xFF, 
  /* ABS: 002 Pixels @ 019,024 */ 0, 2, 0x52, 0x51, 
  /* RLE: 037 Pixels @ 021,024 */ 37, 0xFF, 
  /* ABS: 002 Pixels @ 019,025 */ 0, 2, 0x51, 0x51, 
  /* RLE: 037 Pixels @ 021,025 */ 37, 0xFF, 
  /* ABS: 002 Pixels @ 019,026 */ 0, 2, 0x52, 0x51, 
  /* RLE: 037 Pixels @ 021,026 */ 37, 0xFF, 
  /* ABS: 002 Pixels @ 019,027 */ 0, 2, 0x52, 0x52, 
  /* RLE: 018 Pixels @ 021,027 */ 18, 0xFF, 
  /* ABS: 002 Pixels @ 000,028 */ 0, 2, 0x3C, 0x43, 
  /* RLE: 017 Pixels @ 002,028 */ 17, 0xFF, 
  /* ABS: 002 Pixels @ 019,028 */ 0, 2, 0x51, 0x52, 
  /* RLE: 016 Pixels @ 021,028 */ 16, 0xFF, 
  /* ABS: 005 Pixels @ 037,028 */ 0, 5, 0x43, 0x3C, 0xC5, 0x15, 0x80, 
  /* RLE: 016 Pixels @ 003,029 */ 16, 0xFF, 
  /* ABS: 002 Pixels @ 019,029 */ 0, 2, 0x52, 0x52, 
  /* RLE: 015 Pixels @ 021,029 */ 15, 0xFF, 
  /* ABS: 007 Pixels @ 036,029 */ 0, 7, 0x80, 0x15, 0xC5, 0xFF, 0x85, 0x14, 0xB2, 
  /* RLE: 015 Pixels @ 004,030 */ 15, 0xFF, 
  /* ABS: 002 Pixels @ 019,030 */ 0, 2, 0x51, 0x51, 
  /* RLE: 014 Pixels @ 021,030 */ 14, 0xFF, 
  /* ABS: 009 Pixels @ 035,030 */ 0, 9, 0xB2, 0x14, 0x85, 0xFF, 0xFF, 0xFF, 0x64, 0x23, 0xCF, 
  /* RLE: 014 Pixels @ 005,031 */ 14, 0xFF, 
  /* ABS: 002 Pixels @ 019,031 */ 0, 2, 0x52, 0x52, 
  /* RLE: 013 Pixels @ 021,031 */ 13, 0xFF, 
  /* ABS: 003 Pixels @ 034,031 */ 0, 3, 0xCF, 0x23, 0x64, 
  /* RLE: 005 Pixels @ 037,031 */ 5, 0xFF, 
  /* ABS: 003 Pixels @ 003,032 */ 0, 3, 0x5B, 0x23, 0xB2, 
  /* RLE: 013 Pixels @ 006,032 */ 13, 0xFF, 
  /* ABS: 002 Pixels @ 019,032 */ 0, 2, 0x52, 0x52, 
  /* RLE: 012 Pixels @ 021,032 */ 12, 0xFF, 
  /* ABS: 003 Pixels @ 033,032 */ 0, 3, 0xB2, 0x23, 0x5B, 
  /* RLE: 007 Pixels @ 036,032 */ 7, 0xFF, 
  /* ABS: 003 Pixels @ 004,033 */ 0, 3, 0x64, 0x14, 0x80, 
  /* RLE: 012 Pixels @ 007,033 */ 12, 0xFF, 
  /* ABS: 002 Pixels @ 019,033 */ 0, 2, 0x51, 0x51, 
  /* RLE: 011 Pixels @ 021,033 */ 11, 0xFF, 
  /* ABS: 003 Pixels @ 032,033 */ 0, 3, 0x80, 0x14, 0x64, 
  /* RLE: 009 Pixels @ 035,033 */ 9, 0xFF, 
  /* ABS: 004 Pixels @ 005,034 */ 0, 4, 0x85, 0x15, 0x43, 0xCE, 
  /* RLE: 010 Pixels @ 009,034 */ 10, 0xFF, 
  /* ABS: 002 Pixels @ 019,034 */ 0, 2, 0x51, 0x52, 
  /* RLE: 009 Pixels @ 021,034 */ 9, 0xFF, 
  /* ABS: 004 Pixels @ 030,034 */ 0, 4, 0xCE, 0x43, 0x15, 0x85, 
  /* RLE: 011 Pixels @ 034,034 */ 11, 0xFF, 
  /* ABS: 005 Pixels @ 006,035 */ 0, 5, 0xC5, 0x3C, 0x11, 0x5C, 0xDC, 
  /* RLE: 008 Pixels @ 011,035 */ 8, 0xFF, 
  /* ABS: 002 Pixels @ 019,035 */ 0, 2, 0x51, 0x52, 
  /* RLE: 007 Pixels @ 021,035 */ 7, 0xFF, 
  /* ABS: 005 Pixels @ 028,035 */ 0, 5, 0xDC, 0x5C, 0x11, 0x3C, 0xC5, 
  /* RLE: 014 Pixels @ 033,035 */ 14, 0xFF, 
  /* ABS: 005 Pixels @ 008,036 */ 0, 5, 0x8E, 0x29, 0x0E, 0x43, 0x9D, 
  /* RLE: 006 Pixels @ 013,036 */ 6, 0xFF, 
  /* ABS: 002 Pixels @ 019,036 */ 0, 2, 0x51, 0x52, 
  /* RLE: 005 Pixels @ 021,036 */ 5, 0xFF, 
  /* ABS: 005 Pixels @ 026,036 */ 0, 5, 0x9D, 0x43, 0x0E, 0x29, 0x8E, 
  /* RLE: 018 Pixels @ 031,036 */ 18, 0xFF, 
  /* ABS: 019 Pixels @ 010,037 */ 0, 19, 0x97, 0x3C, 0x0C, 0x10, 0x32, 0x5F, 0x92, 0xC1, 0xE8, 0x50, 0x4A, 0xC1, 0x92, 0x5F, 0x32, 0x10, 0x0C, 0x3C, 0x97, 
  /* RLE: 022 Pixels @ 029,037 */ 22, 0xFF, 
  /* ABS: 015 Pixels @ 012,038 */ 0, 15, 0xEF, 0x91, 0x4F, 0x26, 0x0F, 0x04, 0x01, 0x00, 0x00, 0x04, 0x0F, 0x26, 0x4F, 0x91, 0xEF, 
  /* RLE: 012 Pixels @ 027,038 */ 12, 0xFF, 
  0
};  // 504 bytes for 1521 pixels

GUI_CONST_STORAGE GUI_BITMAP bmmao = {
  39, // xSize
  39, // ySize
  39, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acmao,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
