/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.24                          *
*        Compiled Jan 27 2014, 11:28:24                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "MainTask.h"
#include "Config.h"
#include "Setting.h"
#include "SystemConfig.h"
#include "GUI.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)

#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_2 (GUI_ID_USER + 0x03)
#define ID_TEXT_3 (GUI_ID_USER + 0x04)
#define ID_TEXT_4 (GUI_ID_USER + 0x05)
#define ID_TEXT_5 (GUI_ID_USER + 0x06)
#define ID_TEXT_6 (GUI_ID_USER + 0x07)
#define ID_TEXT_7 (GUI_ID_USER + 0x08)
#define ID_TEXT_8 (GUI_ID_USER + 0x09)
#define ID_TEXT_9 (GUI_ID_USER + 0x0a)

#define ID_BUTTON_0 (GUI_ID_USER + 0x10)
#define ID_BUTTON_1 (GUI_ID_USER + 0x11)
#define ID_BUTTON_2 (GUI_ID_USER + 0x12)
#define ID_BUTTON_3 (GUI_ID_USER + 0x13)
#define ID_BUTTON_4 (GUI_ID_USER + 0x14)
#define ID_BUTTON_5 (GUI_ID_USER + 0x15)
#define ID_BUTTON_6 (GUI_ID_USER + 0x16)


/*------------------- external variables ------------------------*/
extern char * pStrBuf;

extern WM_HWIN subWins[4];
extern WM_HWIN confirmWin;
extern WM_HWIN menuWin;

extern MNT_BOAT MNT_Boats[BOAT_LIST_SIZE_MAX];
extern short N_monitedBoat;

extern CONF_SYS  SysConf;



/*------------------- external functions ------------------------*/


/*------------------- local    variables -------------------------*/
WM_HWIN btWin ;
WM_HWIN hBts[7];

static int fdDist  = 0;
static int zmDist  = 0;
static void myButtonListener(WM_MESSAGE* pMsg);
static void btReset(WM_HWIN thisWin);

MNT_SETTING mntSetting;
/*------------------- local    functions -------------------------*/
//void printMoniteSetting(void);
//void printSetting(MNT_SETTING * p_setting);
//extern void mntSetting_init(void);



// USER START (Optionally insert additional defines)



// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*   
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "ETWin", ID_WINDOW_0, ETWin_X, SubWin_Y+40, ETWin_WIDHT, ETWin_HEIGHT-40, 0, 0x0, 0 },
	
	{ TEXT_CreateIndirect, "监控设置项:",  ID_TEXT_0, 0,    0,                  ETWin_WIDHT,30, 0, 0x0, 0},
	{ TEXT_CreateIndirect, "消失报警:",   ID_TEXT_1, 0,    LV_MoniteSet_Y,     160,        30, 0, 0x0, 0},
	{ TEXT_CreateIndirect, "防盗报警:",   ID_TEXT_2, 0,    LV_MoniteSet_Y+60,  200,        30, 0, 0x0, 0},
	{ TEXT_CreateIndirect, "报警距离:",   ID_TEXT_3, 0,   LV_MoniteSet_Y+100,  200,         0, 0, 0x0, 0},
 { TEXT_CreateIndirect, "nm",           ID_TEXT_8, 200,  LV_MoniteSet_Y+100,   50,        30, 0, 0x0, 0},
	{ TEXT_CreateIndirect, "报警声音:",   ID_TEXT_4, 0,   LV_MoniteSet_Y+140, 200,        30, 0, 0x0, 0},
	{ TEXT_CreateIndirect, "走锚报警:",   ID_TEXT_5, 0,    LV_MoniteSet_Y+200, 200,        40, 0, 0x0, 0},
	{ TEXT_CreateIndirect, "报警距离:",   ID_TEXT_6, 0,   LV_MoniteSet_Y+240, 200,        40,  0, 0x0, 0},
 { TEXT_CreateIndirect, "nm",           ID_TEXT_9, 200,  LV_MoniteSet_Y+240, 50,         40,  0, 0x0,0},
 { TEXT_CreateIndirect, "报警声音:",   ID_TEXT_7, 0,   LV_MoniteSet_Y+280, 200,        40,  0, 0x0, 0},

 
 { BUTTON_CreateIndirect, "bt_0", ID_BUTTON_0, 130, LV_MoniteSet_Y,     70, 30, 0, 0xa,  0 },
 { BUTTON_CreateIndirect, "bt_1", ID_BUTTON_1, 130, LV_MoniteSet_Y+60,  70, 30, 0, 0x64, 0 },
 { BUTTON_CreateIndirect, "bt_2", ID_BUTTON_2, 130, LV_MoniteSet_Y+100, 70, 30, 0, 0x64, 0 },
 { BUTTON_CreateIndirect, "bt_3", ID_BUTTON_3, 130, LV_MoniteSet_Y+140, 70, 30, 0, 0x64, 0 },
 { BUTTON_CreateIndirect, "bt_4", ID_BUTTON_4, 130, LV_MoniteSet_Y+200, 70, 30, 0, 0x64, 0 },
 { BUTTON_CreateIndirect, "bt_5", ID_BUTTON_5, 130, LV_MoniteSet_Y+240, 70, 30, 0, 0x64, 0},
	{ BUTTON_CreateIndirect, "bt_6", ID_BUTTON_6, 130, LV_MoniteSet_Y+280, 70, 30, 0, 0x64, 0}
	
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
MntSetWin_COLOR MntSetWinSkins[2]  = {
///                                      bkColor         Label     BkUnpressed       Text          TxBk
                                        { GUI_DARKGRAY,  GUI_BLACK,  GUI_DARKGREEN,   GUI_LIGHTGRAY, GUI_BLACK},
                                        { GUI_GRAY,      GUI_GRAY,   GUI_LIGHTGREEN,  GUI_DARKGRAY,  GUI_LIGHTMAGENTA} 
                                       };

MntSetWin_COLOR * pMntSetWinSkin  = MntSetWinSkins;
// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	
	const WM_KEY_INFO* pInfo;
 WM_HWIN  hItem  = 0;
 
  int     i  = 0;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END
  switch (pMsg->MsgId) {
  
  case USER_MSG_SKIN: 
       pMntSetWinSkin  = &(MntSetWinSkins[pMsg->Data.v]);
       
       WINDOW_SetBkColor(pMsg->hWin, pMntSetWinSkin->MntSetWin_BackGround);
       
       hItem  = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
       TEXT_SetTextColor(hItem, pMntSetWinSkin->MntSetWin_Label);
       hItem  = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
       TEXT_SetTextColor(hItem, pMntSetWinSkin->MntSetWin_Label);    
       hItem  = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
       TEXT_SetTextColor(hItem, pMntSetWinSkin->MntSetWin_Label); 
       hItem  = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
       TEXT_SetTextColor(hItem, pMntSetWinSkin->MntSetWin_Label);    
       hItem  = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
       TEXT_SetTextColor(hItem, pMntSetWinSkin->MntSetWin_Label);    
       hItem  = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
       TEXT_SetTextColor(hItem, pMntSetWinSkin->MntSetWin_Label);    
       hItem  = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
       TEXT_SetTextColor(hItem, pMntSetWinSkin->MntSetWin_Label);    
       hItem  = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
       TEXT_SetTextColor(hItem, pMntSetWinSkin->MntSetWin_Label);    
       hItem  = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
       TEXT_SetTextColor(hItem, pMntSetWinSkin->MntSetWin_Label);    
       hItem  = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
       TEXT_SetTextColor(hItem, pMntSetWinSkin->MntSetWin_Label);  

       for(i=0;i<7;i++)
       {
          BUTTON_SetBkColor(hBts[i], BUTTON_CI_UNPRESSED, GUI_GRAY);
          BUTTON_SetTextColor(hBts[i], BUTTON_CI_UNPRESSED,GUI_WHITE);
       }       
  case WM_INIT_DIALOG:
    //
    // Initialization of 'text'
    //    
    hItem  = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextColor(hItem, pMntSetWinSkin->MntSetWin_Label);
    hItem  = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextColor(hItem, pMntSetWinSkin->MntSetWin_Label);    
    hItem  = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextColor(hItem, pMntSetWinSkin->MntSetWin_Label); 
    hItem  = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextColor(hItem, pMntSetWinSkin->MntSetWin_Label);    
    hItem  = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextColor(hItem, pMntSetWinSkin->MntSetWin_Label);    
    hItem  = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetTextColor(hItem, pMntSetWinSkin->MntSetWin_Label);    
    hItem  = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetTextColor(hItem, pMntSetWinSkin->MntSetWin_Label);    
    hItem  = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetTextColor(hItem, pMntSetWinSkin->MntSetWin_Label);    
    hItem  = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetTextColor(hItem, pMntSetWinSkin->MntSetWin_Label);    
    hItem  = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetTextColor(hItem, pMntSetWinSkin->MntSetWin_Label);    
  
    //
    // Initialization of 'et_0'
    //
    
    hBts[0] = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hBts[0], mntSetting.DSP_Setting.isEnable>DISABLE?"开启":"关闭");   
	   WM_SetCallback(hBts[0],&myButtonListener);
    
    //
    // Initialization of 'et_1'
    //
    hBts[1] = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetText(hBts[1], mntSetting.BGL_Setting.isEnable>DISABLE?"开启":"关闭"); 
	   WM_SetCallback(hBts[1],&myButtonListener);  
    //
    // Initialization of 'et_2'
    //
    hBts[2] = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
	  	sprintf(pStrBuf, "%d",mntSetting.BGL_Setting.Dist);
	  	BUTTON_SetText(hBts[2], pStrBuf);  
	   WM_SetCallback(hBts[2],&myButtonListener);	
    //
    // Initialization of 'et_3'
    //
    hBts[3] = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetText(hBts[3], mntSetting.BGL_Setting.isSndEnable>DISABLE?"开启":"关闭");
	   WM_SetCallback(hBts[3] ,&myButtonListener);	  
    //
    // Initialization of 'et_4'
    //
    hBts[4]  = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetText(hBts[4], mntSetting.DRG_Setting.isEnable>DISABLE?"开启":"关闭");
	   WM_SetCallback(hBts[4],&myButtonListener);    
    //
    // Initialization of 'et_5'
    //
    hBts[5]  = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);   
    sprintf(pStrBuf, "%d",mntSetting.DRG_Setting.Dist);
    BUTTON_SetText(hBts[5], pStrBuf);     
    WM_SetCallback(hBts[5],&myButtonListener);
    
    
    hBts[6]  = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
    BUTTON_SetText(hBts[6], mntSetting.DRG_Setting.isSndEnable>DISABLE?"开启":"关闭");
    WM_SetCallback(hBts[6], &myButtonListener);;
    
    for(i=0;i<7;i++)
    {
//       BUTTON_SetBkColor(hBts[i], BUTTON_CI_UNPRESSED, pMntSetWinSkin->);
       BUTTON_SetTextColor(hBts[i], BUTTON_CI_UNPRESSED,GUI_WHITE);
    } 
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;

	
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'et_0'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'et_1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'et_2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'et_3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'et_4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateETWin
*/
WM_HWIN bttWinCreate(void);
WM_HWIN btWinCreate(void) {

//  btWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, subWins[1], 0, 0);
  btWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return btWin;
}

// USER START (Optionally insert additional public code)

static void myButtonListener(WM_MESSAGE* pMsg)
{
	const WM_KEY_INFO* pInfo;
	WM_MESSAGE myMsg;
	WM_HWIN thisButton = pMsg->hWin;
	
	WM_HWIN focussedButton  = 0;
	
	int i  = 0;
	int Step  = 0;

	
	switch(pMsg->MsgId)
	{
		case WM_KEY:
			pInfo  = (WM_KEY_INFO*)pMsg->Data.p;
		
		  switch(pInfo->Key)
			{
				case GUI_KEY_UP:
					GUI_StoreKeyMsg(GUI_KEY_BACKTAB,1);
					break;
				
				case GUI_KEY_DOWN:
					GUI_StoreKeyMsg(GUI_KEY_TAB,1);
					break;
		
    case GUI_KEY_RIGHT:
         Step  = 10;
    case GUI_KEY_LEFT:
         Step  = (Step>5)?5:-5;
         focussedButton  = WM_GetFocussedWindow();
         while( (focussedButton != hBts[i])  &&  (i<7) )
              i++;

         switch(i)
         {
            case 0:
                 if(mntSetting.DSP_Setting.isEnable)
                 {
                    mntSetting.DSP_Setting.isEnable  = DISABLE;
                    BUTTON_SetText(hBts[0], "关闭");
                 }
                 else
                 {
                    mntSetting.DSP_Setting.isEnable  = ENABLE;
                    BUTTON_SetText(hBts[0], "开启");
                 }
                 break;
                 
            case 1:
                 if(mntSetting.BGL_Setting.isEnable)
                 {
                    mntSetting.BGL_Setting.isEnable  = DISABLE;
                    BUTTON_SetText(hBts[1], "关闭");
                 }
                 else
                 {
                    mntSetting.BGL_Setting.isEnable  = ENABLE;
                    BUTTON_SetText(hBts[1], "开启");
                 }
                 break;
                 
            case 2:
                 mntSetting.BGL_Setting.Dist  += Step;
                 mntSetting.BGL_Setting.Dist  = (mntSetting.BGL_Setting.Dist+105)%105;
                 
                 sprintf(pStrBuf, "%d.%02d", mntSetting.BGL_Setting.Dist/100, mntSetting.BGL_Setting.Dist%100);
                 BUTTON_SetText(hBts[2], pStrBuf);
                 break;
                 
            case 3:
                 if(mntSetting.BGL_Setting.isSndEnable) 
                 {                 
                    mntSetting.BGL_Setting.isSndEnable = DISABLE;
                    BUTTON_SetText(hBts[3], "关闭");
                 } 
                 else
                 {                
                    mntSetting.BGL_Setting.isSndEnable  = ENABLE;
                    BUTTON_SetText(hBts[3], "开启");
                 }                   
                 break;  
            case 4:
                 if(mntSetting.DRG_Setting.isEnable)
                 { 
                    mntSetting.DRG_Setting.isEnable  = DISABLE;
                    BUTTON_SetText(hBts[4], "关闭");
                 }
                 else
                 {
                    mntSetting.DRG_Setting.isEnable  = ENABLE;
                    BUTTON_SetText(hBts[4], "开启");
                 }
                 break;            
                 
            case 5:
                 mntSetting.DRG_Setting.Dist  += Step;
                 mntSetting.DRG_Setting.Dist  = (mntSetting.DRG_Setting.Dist+105)%105;
                 
                 sprintf(pStrBuf, "%d.%02d", mntSetting.DRG_Setting.Dist/100, mntSetting.DRG_Setting.Dist%100);
                 BUTTON_SetText(hBts[5], pStrBuf);
                 break; 
            
            case 6:
                 if(mntSetting.DRG_Setting.isSndEnable)
                 {
                    mntSetting.DRG_Setting.isSndEnable  = DISABLE;
                    BUTTON_SetText(hBts[6], "关闭");
                 }
                 else
                 {
                    mntSetting.DRG_Setting.isSndEnable  = ENABLE;
                    BUTTON_SetText(hBts[6], "开启");
                 }
                 break;            
                 
         }
         break;
    	
    case GUI_KEY_BACKSPACE:
         myMsg.hWin  = WM_GetClientWindow(confirmWin);
         myMsg.hWinSrc  = pMsg->hWin;
         myMsg.MsgId  = USER_MSG_ID_CHOOSE;
         myMsg.Data.v = STORE_SETTING;
         WM_SendMessage(myMsg.hWin, &myMsg);
         
         WM_BringToTop(confirmWin);
         WM_SetFocus(confirmWin);
    break; 
         
				default:
					BUTTON_Callback(pMsg);
				break;
			}
   break;
			
   case USER_MSG_ID_REPLY:
       switch(pMsg->Data.v)
       {
          case REPLY_OK:
               MNT_makeSettingUp(&mntSetting);  
               MNT_init(&mntSetting);
               btReset(btWin);
               printMoniteSetting(MNT_Boats);              
               WM_SetFocus(menuWin);
               break;
          case REPLY_CANCEL:         
               WM_SetFocus(subWins[1]);
               break;
               
           default:
INFO("Something err!");           
           break;
       }
 
   break;
       
				default:
					BUTTON_Callback(pMsg);
				break;
	}	 
  
}

// USER END

static void btReset(WM_HWIN thisWin)
{
   BUTTON_SetText(hBts[0], mntSetting.DSP_Setting.isEnable>DISABLE?"开启":"关闭");   
   BUTTON_SetText(hBts[1], mntSetting.BGL_Setting.isEnable>DISABLE?"开启":"关闭"); 
   sprintf(pStrBuf, "%d.%02d", mntSetting.BGL_Setting.Dist/100, mntSetting.BGL_Setting.Dist%100);
   BUTTON_SetText(hBts[2], pStrBuf); 
   BUTTON_SetText(hBts[3], mntSetting.BGL_Setting.isSndEnable>DISABLE?"开启":"关闭"); 
   BUTTON_SetText(hBts[4], mntSetting.DRG_Setting.isEnable>DISABLE?"开启":"关闭"); 
   sprintf(pStrBuf, "%d.%02d", mntSetting.DRG_Setting.Dist/100, mntSetting.DRG_Setting.Dist%100);
   BUTTON_SetText(hBts[5], pStrBuf);  
   BUTTON_SetText(hBts[6], mntSetting.DRG_Setting.isSndEnable>DISABLE?"开启":"关闭");    
}





/*************************** End of file ****************************/
