/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.24                          *
*        Compiled Jan 27 2014, 11:28:24                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include <UCOS_II.h>
#include "Config.h"
#include "MainTask.h"
#include "Setting.h"

/* --- Macro defines ---*/


/*--- external variables ---*/
extern BERTH * pHeader;
extern SIMP_BERTH SimpBerthes[BOAT_LIST_SIZE_MAX];
extern MNT_BOAT MNT_Boats[MNT_NUM_MAX];

/*--- external functions ---*/
//extern boat* boat_list_p[BOAT_LIST_SIZE_MAX];

/*--- local variables ---*/

/*--- local functions ---*/
static void updateListViewContent(WM_HWIN thisHandle);





/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)
#define ID_LISTVIEW_0   (GUI_ID_USER + 0x01)

#define ID_TEXT_0     (GUI_ID_USER + 0x02)
#define ID_TEXT_1     (GUI_ID_USER + 0x03)
#define ID_TEXT_2     (GUI_ID_USER + 0x04)
#define ID_TEXT_3     (GUI_ID_USER + 0x05)
#define ID_TEXT_4     (GUI_ID_USER + 0x06)
#define ID_TEXT_5     (GUI_ID_USER + 0x07)
#define ID_TEXT_6     (GUI_ID_USER + 0x08)
#define ID_TEXT_7     (GUI_ID_USER + 0x09)
#define ID_TEXT_8     (GUI_ID_USER + 0x0a)


/*---------------- external variables ---------------------------*/
//extern _boat* boat_list_p[BOAT_LIST_SIZE_MAX];
extern _boat  boat_list[BOAT_LIST_SIZE_MAX];


extern short N_boat;
extern short N_monitedBoat;
extern unsigned char* pStrBuf;

extern WM_HWIN menuWin;
extern WM_HWIN subWins[4];
extern OS_EVENT * Updater;
extern uint8_t myErr_2;




/*---------------- external functions --------------------------*/
extern void myftoa(unsigned char * str, float num);



/*---------------- loacal variables ----------------------------*/


/*---------------- local functions -----------------------------*/
static void myListViewListener(WM_MESSAGE* pMsg);
static void updateListViewContent(WM_HWIN thisHandle);
//static void showSelectedBoatInfo(WM_HWIN thisHandle);
int getSelectedBoatIndex(WM_HWIN thisHandle, int col, int row);
void disttostr(unsigned char * str, long num);


/*---------------- static variables ----------------------------*/
static int Index  = -1; //模块变量
static int SelRow  = 0;
static int TotalRows  = 0;
static WM_HTIMER allListRefshTimer;

static GUI_RECT infoRect  = {LV_AllList_WIDTH,LV_AllList_Y,Win_Main_WIDTH-MenuLabel_WIDTH,480};
static GUI_RECT lvIndicate  ={LV_AllList_WIDTH-200,LV_AllList_Y-40,Win_Main_WIDTH-MenuLabel_WIDTH,480};
static GUI_RECT lvRect   = {0,LV_AllList_Y,LV_AllList_WIDTH,LV_AllList_HEIGHT};






// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect,   "Window",          ID_WINDOW_0,   SubWin_X,         SubWin_Y,        SubWin_WIDTH, SubWin_HEIGHT, 0, 0x0, 0},
  { LISTVIEW_CreateIndirect, "Listview",        ID_LISTVIEW_0, LV_AllList_X,     LV_AllList_Y,    LV_AllList_WIDTH, LV_AllList_HEIGHT, 0, 0x0, 0 },
	
	{ TEXT_CreateIndirect,     "All List",        ID_TEXT_0,     LV_AllList_X,     LV_AllList_Y-30,  200,  30, 0, 0x0, 0},
	{ TEXT_CreateIndirect,     "All boats info",  ID_TEXT_1,     LV_AllList_WIDTH, LV_AllList_Y-40,  200,  30, 0, 0x0, 0},
	{ TEXT_CreateIndirect,     "Name:",           ID_TEXT_2,     LV_AllList_WIDTH, LV_AllList_Y+40,  200,  30, 0, 0x0, 0},
	{ TEXT_CreateIndirect,     "N:",              ID_TEXT_3,     LV_AllList_WIDTH, LV_AllList_Y+80,  200,  30, 0, 0x0, 0},
	{ TEXT_CreateIndirect,     "E:",              ID_TEXT_4,     LV_AllList_WIDTH, LV_AllList_Y+120, 200,  30, 0, 0x0, 0},
	{ TEXT_CreateIndirect,     "SOG:",            ID_TEXT_5,     LV_AllList_WIDTH, LV_AllList_Y+160, 200,  30, 0, 0x0, 0},
	{ TEXT_CreateIndirect,     "XSAlarm:",        ID_TEXT_6,     LV_AllList_WIDTH, LV_AllList_Y+200, 200,  30, 0, 0x0, 0},
	{ TEXT_CreateIndirect,     "FDAlarm:",        ID_TEXT_7,     LV_AllList_WIDTH, LV_AllList_Y+240, 200,  30, 0, 0x0, 0},
	{ TEXT_CreateIndirect,     "ZMAlarm:",        ID_TEXT_8,     LV_AllList_WIDTH, LV_AllList_Y+280, 200,  30, 0, 0x0, 0}
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/




// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  int     i  = 0;
  int     SelectedRow  = -1;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {	
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, 0x00FFFF00);
    //
    // Initialization of 'Listview'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
	   WM_SetCallback(hItem, &myListViewListener);
	  
	   LISTVIEW_SetFont(hItem, &GUI_Font28);
    LISTVIEW_AddColumn(hItem, LV_AllList_Col_0_WIDTH, "Dis", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, LV_AllList_Col_1_WIDTH, "Ang", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, LV_AllList_Col_2_WIDTH, "MMSI", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, LV_AllList_Col_3_WIDTH, "State", GUI_TA_HCENTER | GUI_TA_VCENTER);	
    LISTVIEW_AddRow(hItem, NULL);
    LISTVIEW_SetGridVis(hItem, 1);
	   LISTVIEW_SetHeaderHeight(hItem,LV_MoniteList_Header_HEIGHT);
	   LISTVIEW_SetRowHeight(hItem,LV_MoniteList_Row_HEIGHT);
	
    LISTVIEW_SetFont(hItem, &GUI_Font24B_1);
    LISTVIEW_SetTextColor(hItem, LISTVIEW_CI_UNSEL,GUI_WHITE);
    LISTVIEW_SetBkColor(hItem, LISTVIEW_CI_UNSEL,DEEPBLUE);
    LISTVIEW_SetTextColor(hItem, LISTVIEW_CI_SELFOCUS,GUI_BLACK);
    LISTVIEW_SetBkColor(hItem, LISTVIEW_CI_SELFOCUS, GUI_WHITE);
    LISTVIEW_SetBkColor(hItem, LISTVIEW_CI_SEL, DEEPBLUE);
    LISTVIEW_SetAutoScrollV(hItem,1);
   
    updateListViewContent(hItem);
    
    allListRefshTimer  = WM_CreateTimer(pMsg->hWin, 1, 5000, 0);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
case WM_TIMER:
   updateListViewContent(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0));
   WM_RestartTimer(allListRefshTimer,5000);
break;    
		
case WM_PAINT:

//    updateListViewContent(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0));

     GUI_SetFont(&GUI_Font24_1);
     GUI_SetColor(GUI_YELLOW);
     GUI_SetTextMode(GUI_TM_TRANS);
	  
     SelectedRow  = LISTVIEW_GetSel(WM_GetDialogItem(pMsg->hWin,ID_LISTVIEW_0)); 

        sprintf(pStrBuf,"%3d/%3d",SelectedRow+1,TotalRows);
        GUI_DispStringAt(pStrBuf,LV_AllList_WIDTH-200,LV_AllList_Y-40);
       
        GUI_DispStringAt(SimpBerthes[SelectedRow].pBoat->name,LV_AllList_WIDTH+50,80);       
       
        lltostr(SimpBerthes[SelectedRow].pBoat->latitude,pStrBuf);
        GUI_DispStringExAt(pStrBuf,LV_AllList_WIDTH+20,120);	
        
        lltostr(SimpBerthes[SelectedRow].pBoat->longitude,pStrBuf);
        GUI_DispStringExAt(pStrBuf,LV_AllList_WIDTH+20,160);
        
        GUI_DispDecAt(SimpBerthes[SelectedRow].pBoat->SOG,LV_AllList_WIDTH+80,200,3);    




		break;		
		
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_LISTVIEW_0: // Notifications sent by 'Listview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
			  // WM_InvalidateRect(pMsg->hWin,&infoRect);		// 可以,但逻辑不对			
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN sub2WinCreate(void);
WM_HWIN sub2WinCreate(void) {
  WM_HWIN hWin;
	

//  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, menuWin, 0, 0);
hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END


static void myListViewListener(WM_MESSAGE* pMsg)
{
	const WM_KEY_INFO* pInfo;
	WM_HWIN thisListView  = pMsg->hWin;
 
 int selectedRow  = -1;
 int totalRows  = 0;
	int i  = 0;
 int insertNum  = 0;
 long Id  = 0;
	switch(pMsg->MsgId)
	{
		case WM_SET_FOCUS:

      if(LISTVIEW_GetNumRows(pMsg->hWin) && (LISTVIEW_GetSel(pMsg->hWin)<0))
         LISTVIEW_SetSel(pMsg->hWin, 0);
      
         LISTVIEW_Callback(pMsg);
         WM_InvalidateRect(subWins[2],&lvRect);
         WM_InvalidateRect(subWins[2],&lvIndicate); 
      break;	    
    
    case WM_KEY:
			pInfo  = (WM_KEY_INFO*)pMsg->Data.p;
		  
		  switch(pInfo->Key)
			{
				case GUI_KEY_UP:
				case GUI_KEY_DOWN:
				     LISTVIEW_Callback(pMsg);
         WM_InvalidateRect(subWins[2],&lvRect);
         WM_InvalidateRect(subWins[2],&lvIndicate);          
				    	break;
				
    case GUI_KEY_RIGHT:
    
         selectedRow  = LISTVIEW_GetSel(thisListView);
         totalRows    = LISTVIEW_GetNumRows(thisListView);
         LISTVIEW_SetSel(thisListView, totalRows);
         if(selectedRow/10 < totalRows/10)
            LISTVIEW_SetSel(thisListView,selectedRow-selectedRow%10+10);
         WM_InvalidateRect(subWins[2],&lvRect);
         WM_InvalidateRect(subWins[2],&lvIndicate); 
         break;
         
    case GUI_KEY_LEFT:
         selectedRow  = LISTVIEW_GetSel(thisListView);
         totalRows    = LISTVIEW_GetNumRows(thisListView);
         if(selectedRow >9 )
         {
            LISTVIEW_SetSel(thisListView, totalRows);
            LISTVIEW_SetSel(thisListView,selectedRow-selectedRow%10-10);
         }
         WM_InvalidateRect(subWins[2],&lvRect);
         WM_InvalidateRect(subWins[2],&lvIndicate); 

            
//         showSelectedBoatInfo(thisListView);
         break;
    
				case GUI_KEY_BACKSPACE:
         for(i=0;i<N_boat;i++) 
         {
            if(MNTState_Choosen == SimpBerthes[i].pBoat->mntStates)
            {
INFO("insert name:%s",SimpBerthes[i].pBoat->name);            
               insertNum  = MNT_insert(MNT_Boats,
                             SimpBerthes[i].pBoat->user_id, 
                             SimpBerthes[i].pBoat->name);
               if( insertNum < 0 )
               {
INFO("MNT_insert failed!");  
                  break;                              
               }
               else
               {
                  SimpBerthes[i].pBoat->mntStates  = MNTState_Monited;
               }
            }            
         }       
         WM_SetFocus(menuWin);
         break;
 
    case GUI_KEY_ENTER:
         selectedRow  = LISTVIEW_GetSel(thisListView);
         
         LISTVIEW_GetItemText(thisListView, 2, selectedRow, pStrBuf, 10);
         Id  = strtoi(pStrBuf);
         
//         OSMutexPend(Updater, 0, &myErr_2);
         for(i=0;i<N_boat;i++)
         {
     
            if(SimpBerthes[i].pBoat->user_id == Id)
            {          
               break;
            }
         }
         
         
         if(MNTState_None == SimpBerthes[i].pBoat->mntStates)
         {
       
            SimpBerthes[i].pBoat->mntStates  = MNTState_Choosen;
            LISTVIEW_SetItemText(thisListView, 3, selectedRow, "Y");
         }
         else if(MNTState_Choosen  == SimpBerthes[i].pBoat->mntStates)
         {
     
            SimpBerthes[i].pBoat->mntStates  = MNTState_None;
            LISTVIEW_SetItemText(thisListView, 3, selectedRow, "N");
         }
//         OSMutexPost(Updater);
         break;

         
				default:
      LISTVIEW_Callback(pMsg);
      break;
			}
			break;
			
				default:
					LISTVIEW_Callback(pMsg);
					break;
	}
}



/* 更新所有船舶列表的条目
*
*/
static void updateListViewContent(WM_HWIN thisHandle)
{	
	WM_HWIN thisListView  = thisHandle;
	
	int i  = 0;
	int NumOfRows  = 0;
 int SelectedRow  = -1;
 long Id  = 0;
 
 BERTH * pTmp  = NULL;

   SelectedRow  = LISTVIEW_GetSel(thisListView);
 
   LISTVIEW_GetItemText(thisListView, 2, SelectedRow, pStrBuf, 10);
   Id  = strtoi(pStrBuf);

   pTmp  = pHeader;
  
	  NumOfRows  = LISTVIEW_GetNumRows(thisListView);
	
   for(i=0;i<N_boat;i++)
   {

      if(i+1 > NumOfRows)
      {
         LISTVIEW_AddRow(thisListView, NULL);
         NumOfRows  = LISTVIEW_GetNumRows(thisListView);
      }
      if(SimpBerthes[i].pBoat->user_id == Id)
       {
      
          SelectedRow  = i;      
       }
//      sprintf(pStrBuf, "%d", SimpBerthes[i].Dist);
      disttostr(pStrBuf, SimpBerthes[i].Dist);
      LISTVIEW_SetItemText(thisListView, 0, i, pStrBuf);
      
      sprintf(pStrBuf, "%09ld", SimpBerthes[i].pBoat->user_id);
      LISTVIEW_SetItemText(thisListView, 2, i, pStrBuf);
      
      if(MNTState_None == SimpBerthes[i].pBoat->mntStates)
      {
         LISTVIEW_SetItemText(thisListView, 3, i, "N");
      }
      else
      {
         LISTVIEW_SetItemText(thisListView, 3, i, "Y");
      }
   }
	
	// LISTVIEW 行数大于要显示的船的数量，删除行
	while(NumOfRows > i+1)
	{
	 	LISTVIEW_DeleteRow(thisListView, NumOfRows-1);
	 	NumOfRows  = LISTVIEW_GetNumRows(thisListView);
	}
	
 LISTVIEW_SetSel(thisListView, SelectedRow);
 TotalRows  = NumOfRows;
    WM_InvalidateRect(subWins[2],&lvRect);
    WM_InvalidateRect(subWins[2],&lvIndicate); 
}


int getSelectedBoatIndex(WM_HWIN thisHandle,int col,int row)
{
   WM_HWIN thisListView  = thisHandle;
   int i  = -1;
   long SelectedId  = 0;
   if(row >= 0)
   {
      LISTVIEW_GetItemText(thisListView, col, row, pStrBuf, 10);
      SelectedId  = strtoi(pStrBuf);
      
//      while( (boat_list_p[i]->user_id!=SelectedId)  &&  (i<N_boat) )
//      {
//          i++;
//      }
   }
   
  return i;
}


//static void showSelectedBoatInfo(WM_HWIN thisHandle)
//{
//	
//	WM_HWIN thisListView  = thisHandle;

//	   Index  = LISTVIEW_GetSel(thisListView);

//    Index  = getSelectedBoatIndex(thisListView, 2, SelectedRow);
//    WM_InvalidateRect(subWins[2],&infoRect);
//    WM_InvalidateRect(subWins[2],&lvIndicate);
////	}
//}

void disttostr(unsigned char * str, long num)
{

   if(num > 99999)
      sprintf(str, "%d.%0d",num/100000,(num%100000)/100);
   else if(num > 9999)
      sprintf(str, "%d.%02d",num/10000, (num%10000)/10);
   else 
      sprintf(str, "%0d.%03d", num/1000, (num%1000));
   
//    int i  = 0;
//    int j  = 0;
//    int subVal  = 0;
//    unsigned tmp  = 0;
//    
//    
//    subVal  = (num*1000)/1;
////printf("\r\nsubVal:%d",subVal);  
//    for(i=0;i<3;i++)
//    {
//       str[i]  = '0'+subVal%10;
//       subVal  = subVal/10;
//    }
//    str[i++]  = '.';
//    subVal  = num/1;

//    str[i++]  = subVal%10 + '0';
//    
//    subVal  = subVal/10;
//    while(subVal)
//    {
//       str[i++]  = subVal%10 + '0';
//       subVal  = subVal/10;
//    }
//    str[i]  = '\0';
//    i--;
//    for (j = 0; j<(i + 1) / 2; j++)
//    {
//     str[j] =      str[j] ^ str[i - j];
//     str[i - j] =  str[j] ^ str[i - j];
//     str[j] =      str[j] ^ str[i - j];

//    }
//    
//    str[5]  = '\0';
////printf("\r\nstr:%s",str);  
}
















/*************************** End of file ****************************/
