/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V5.26.            *
*        Compiled Aug  8 2014, 14:05:55                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: yu                                                    *
* Dimensions:  16 * 41                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmyu;

static GUI_CONST_STORAGE unsigned char _acyu[] = {
  /* RLE: 006 Pixels @ 000,000 */ 6, 0xFF, 
  /* ABS: 004 Pixels @ 006,000 */ 0, 4, 0xD9, 0x08, 0x11, 0xEB, 
  /* RLE: 012 Pixels @ 010,000 */ 12, 0xFF, 
  /* ABS: 004 Pixels @ 006,001 */ 0, 4, 0x78, 0x10, 0x10, 0x78, 
  /* RLE: 011 Pixels @ 010,001 */ 11, 0xFF, 
  /* ABS: 006 Pixels @ 005,002 */ 0, 6, 0x8E, 0x11, 0xA0, 0xA0, 0x11, 0x8E, 
  /* RLE: 009 Pixels @ 011,002 */ 9, 0xFF, 
  /* ABS: 008 Pixels @ 004,003 */ 0, 8, 0xBC, 0x16, 0x7F, 0xFF, 0xFF, 0x7F, 0x16, 0xBC, 
  /* RLE: 008 Pixels @ 012,003 */ 8, 0xFF, 
  /* ABS: 002 Pixels @ 004,004 */ 0, 2, 0x32, 0x4F, 
  /* RLE: 004 Pixels @ 006,004 */ 4, 0xFF, 
  /* ABS: 002 Pixels @ 010,004 */ 0, 2, 0x4F, 0x32, 
  /* RLE: 007 Pixels @ 012,004 */ 7, 0xFF, 
  /* ABS: 003 Pixels @ 003,005 */ 0, 3, 0x6B, 0x20, 0xEF, 
  /* RLE: 004 Pixels @ 006,005 */ 4, 0xFF, 
  /* ABS: 003 Pixels @ 010,005 */ 0, 3, 0xEF, 0x20, 0x6B, 
  /* RLE: 005 Pixels @ 013,005 */ 5, 0xFF, 
  /* ABS: 003 Pixels @ 002,006 */ 0, 3, 0xD5, 0x13, 0x86, 
  /* RLE: 006 Pixels @ 005,006 */ 6, 0xFF, 
  /* ABS: 003 Pixels @ 011,006 */ 0, 3, 0x86, 0x13, 0xD5, 
  /* RLE: 004 Pixels @ 014,006 */ 4, 0xFF, 
  /* ABS: 033 Pixels @ 002,007 */ 0, 33, 0x55, 0x2E, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0x2E, 0x55, 0xFF, 0xFF, 0xFF, 0xE2, 0x10, 0x8F, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0x8F, 0x10, 0xE2, 0xFF, 0xFF, 0x6F, 0x1E, 
  /* RLE: 010 Pixels @ 003,009 */ 10, 0xFF, 
  /* ABS: 006 Pixels @ 013,009 */ 0, 6, 0x1E, 0x6F, 0xFF, 0xFF, 0x26, 0x5F, 
  /* RLE: 010 Pixels @ 003,010 */ 10, 0xFF, 
  /* ABS: 006 Pixels @ 013,010 */ 0, 6, 0x5F, 0x26, 0xFF, 0xD1, 0x02, 0x14, 
  /* RLE: 010 Pixels @ 003,011 */ 10, 0x1A, 
  /* ABS: 005 Pixels @ 013,011 */ 0, 5, 0x14, 0x00, 0x43, 0x7E, 0x07, 
  /* RLE: 012 Pixels @ 002,012 */ 12, 0x1A, 
  /* ABS: 004 Pixels @ 014,012 */ 0, 4, 0x02, 0x29, 0x44, 0x3B, 
  /* RLE: 012 Pixels @ 002,013 */ 12, 0xFF, 
  /* ABS: 004 Pixels @ 014,013 */ 0, 4, 0x3B, 0x44, 0x21, 0x68, 
  /* RLE: 012 Pixels @ 002,014 */ 12, 0xFF, 
  /* ABS: 004 Pixels @ 014,014 */ 0, 4, 0x68, 0x21, 0x0D, 0x9A, 
  /* RLE: 012 Pixels @ 002,015 */ 12, 0xFF, 
  /* ABS: 004 Pixels @ 014,015 */ 0, 4, 0x9A, 0x0D, 0x04, 0xC7, 
  /* RLE: 012 Pixels @ 002,016 */ 12, 0xFF, 
  /* ABS: 004 Pixels @ 014,016 */ 0, 4, 0xC7, 0x04, 0x00, 0xE9, 
  /* RLE: 012 Pixels @ 002,017 */ 12, 0xFF, 
  /* ABS: 004 Pixels @ 014,017 */ 0, 4, 0xE9, 0x00, 0x00, 0xFD, 
  /* RLE: 012 Pixels @ 002,018 */ 12, 0xFF, 
  /* ABS: 004 Pixels @ 014,018 */ 0, 4, 0xFD, 0x00, 0x00, 0xE9, 
  /* RLE: 012 Pixels @ 002,019 */ 12, 0xFF, 
  /* ABS: 004 Pixels @ 014,019 */ 0, 4, 0xE9, 0x00, 0x04, 0xC7, 
  /* RLE: 012 Pixels @ 002,020 */ 12, 0xFF, 
  /* ABS: 004 Pixels @ 014,020 */ 0, 4, 0xC7, 0x04, 0x0D, 0x9A, 
  /* RLE: 012 Pixels @ 002,021 */ 12, 0xFF, 
  /* ABS: 004 Pixels @ 014,021 */ 0, 4, 0x9A, 0x0D, 0x21, 0x68, 
  /* RLE: 012 Pixels @ 002,022 */ 12, 0xFF, 
  /* ABS: 004 Pixels @ 014,022 */ 0, 4, 0x68, 0x21, 0x44, 0x3B, 
  /* RLE: 012 Pixels @ 002,023 */ 12, 0xFF, 
  /* ABS: 004 Pixels @ 014,023 */ 0, 4, 0x3B, 0x44, 0x7E, 0x17, 
  /* RLE: 012 Pixels @ 002,024 */ 12, 0xFF, 
  /* ABS: 005 Pixels @ 014,024 */ 0, 5, 0x17, 0x7E, 0xD1, 0x05, 0xC0, 
  /* RLE: 010 Pixels @ 003,025 */ 10, 0xFF, 
  /* ABS: 006 Pixels @ 013,025 */ 0, 6, 0xC0, 0x05, 0xD1, 0xFF, 0x26, 0x5F, 
  /* RLE: 010 Pixels @ 003,026 */ 10, 0xFF, 
  /* ABS: 006 Pixels @ 013,026 */ 0, 6, 0x5F, 0x26, 0xFF, 0xFF, 0x6F, 0x1E, 
  /* RLE: 010 Pixels @ 003,027 */ 10, 0xFF, 
  /* ABS: 007 Pixels @ 013,027 */ 0, 7, 0x1E, 0x6F, 0xFF, 0xFF, 0xE2, 0x10, 0x8F, 
  /* RLE: 008 Pixels @ 004,028 */ 8, 0xFF, 
  /* ABS: 008 Pixels @ 012,028 */ 0, 8, 0x8F, 0x10, 0xE2, 0xFF, 0xFF, 0xFF, 0x55, 0x2E, 
  /* RLE: 008 Pixels @ 004,029 */ 8, 0xFF, 
  /* ABS: 002 Pixels @ 012,029 */ 0, 2, 0x2E, 0x55, 
  /* RLE: 004 Pixels @ 014,029 */ 4, 0xFF, 
  /* ABS: 003 Pixels @ 002,030 */ 0, 3, 0xD5, 0x13, 0x86, 
  /* RLE: 006 Pixels @ 005,030 */ 6, 0xFF, 
  /* ABS: 003 Pixels @ 011,030 */ 0, 3, 0x86, 0x13, 0xD5, 
  /* RLE: 005 Pixels @ 014,030 */ 5, 0xFF, 
  /* ABS: 003 Pixels @ 003,031 */ 0, 3, 0x6B, 0x20, 0xEF, 
  /* RLE: 004 Pixels @ 006,031 */ 4, 0xFF, 
  /* ABS: 003 Pixels @ 010,031 */ 0, 3, 0xEF, 0x20, 0x6B, 
  /* RLE: 007 Pixels @ 013,031 */ 7, 0xFF, 
  /* ABS: 002 Pixels @ 004,032 */ 0, 2, 0x32, 0x4F, 
  /* RLE: 004 Pixels @ 006,032 */ 4, 0xFF, 
  /* ABS: 002 Pixels @ 010,032 */ 0, 2, 0x4F, 0x32, 
  /* RLE: 008 Pixels @ 012,032 */ 8, 0xFF, 
  /* ABS: 008 Pixels @ 004,033 */ 0, 8, 0xBC, 0x16, 0x7F, 0xFF, 0xFF, 0x7F, 0x16, 0xBC, 
  /* RLE: 009 Pixels @ 012,033 */ 9, 0xFF, 
  /* ABS: 006 Pixels @ 005,034 */ 0, 6, 0x8E, 0x11, 0xA0, 0xA0, 0x11, 0x8E, 
  /* RLE: 011 Pixels @ 011,034 */ 11, 0xFF, 
  /* ABS: 004 Pixels @ 006,035 */ 0, 4, 0x78, 0x10, 0x10, 0x78, 
  /* RLE: 012 Pixels @ 010,035 */ 12, 0xFF, 
  /* ABS: 004 Pixels @ 006,036 */ 0, 4, 0x7F, 0x08, 0x08, 0x7F, 
  /* RLE: 010 Pixels @ 010,036 */ 10, 0xFF, 
  /* ABS: 008 Pixels @ 004,037 */ 0, 8, 0xEF, 0x4F, 0x16, 0x8E, 0x8E, 0x16, 0x4F, 0xEF, 
  /* RLE: 007 Pixels @ 012,037 */ 7, 0xFF, 
  /* ABS: 010 Pixels @ 003,038 */ 0, 10, 0x86, 0x20, 0x32, 0xBC, 0xFF, 0xFF, 0xBC, 0x32, 0x20, 0x86, 
  /* RLE: 004 Pixels @ 013,038 */ 4, 0xFF, 
  /* ABS: 004 Pixels @ 001,039 */ 0, 4, 0x8F, 0x2E, 0x13, 0x6B, 
  /* RLE: 006 Pixels @ 005,039 */ 6, 0xFF, 
  /* ABS: 009 Pixels @ 011,039 */ 0, 9, 0x6B, 0x13, 0x2E, 0x8F, 0xFF, 0x2D, 0x10, 0x55, 0xD5, 
  /* RLE: 008 Pixels @ 004,040 */ 8, 0xFF, 
  /* ABS: 004 Pixels @ 012,040 */ 0, 4, 0xD5, 0x55, 0x10, 0xFF, 
  0
};  // 431 bytes for 656 pixels

GUI_CONST_STORAGE GUI_BITMAP bmyu = {
  16, // xSize
  41, // ySize
  16, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acyu,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
